💡 **Environment:** `clamp-analyses`

# Description

**Per-tissue drug-disease metrics** (NEXT_STEPS Active concern #1 — the "max across 49 tissues"
ablation).

The pipeline collapses each (drug, disease) pair's 49 tissue scores with a **max** before computing
a single pooled AUROC (`../signif_test/00_aggregate_predictions.ipynb`). `max` encodes the hypothesis
"one relevant tissue carries the signal for this pair." Replacing it with mean/median is *not* a
clean ablation (it tests a different, broad-sharing model). The clean instrument — the alternative
the memo itself suggested — is to compute **per-tissue AUROC/AUPRC and then aggregate across
tissues**: this decomposes *where* the signal lives and removes the per-pair tissue-selection step
entirely.

This notebook reproduces the upstream aggregation **up to but not including the max** (rank within
each tissue's DOID distribution → mean across the 5 `n_top_genes` thresholds), then scores **each
tissue independently** over the 685-pair gold-standard universe. It is a **read-only consumer** of
the NB06–09 prediction HDF5s and `../signif_test/predictions_paired.pkl`; it does **not** modify
NB06–13, `libs/`, or the scoring convention. It **fails loud** if any of NB06–NB09 is missing or
incomplete (the 49-tissue completeness asserts are copied verbatim from `signif_test/00`).

Outputs:
- `per_tissue_scores.pkl` — the pre-max long frame `[trait, drug, method, tissue, score, true_class]`
  (685 × 4 × 49 = 133,540 rows), reusable for the deferred tissue-selection analysis.
- `per_tissue_metrics.csv` — AUROC / AUPRC / `auprc_log2_enrich` per `(method, tissue)` (4 × 49 = 196 rows).
- `max_aggregate_reference.csv` — the status-quo max-aggregate AUROC/AUPRC per method (0.583 / 0.625
  / 0.602 / 0.612), carried forward as the reference the per-tissue results are contrasted against.

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from IPython.display import display

import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import roc_auc_score, average_precision_score

from pyprojroot import here

# Settings

In [3]:
N_TISSUES = 49

# Fixed method order / sign convention (matches ../signif_test and ../per_disease_test).
METHOD_ORDER = [
    'gene_based',
    'module_based_archs4',
    'module_based_gtex',
    'module_based_recount2',
]

# Method -> canonical name (copied verbatim from signif_test/00). NB06-NB09 already
# write the canonical names, so these display-name aliases are only a defensive
# fallback (the .get() default passes canonical names through).
METHOD_RENAME = {
    'Gene-based':              'gene_based',
    'Module-based (ARCHS4)':   'module_based_archs4',
    'Module-based (GTEx)':     'module_based_gtex',
    'Module-based (recount2)': 'module_based_recount2',
}

# All four methods in the full grid (gene baseline + three module models).
METHOD_THRESHOLDS = {
    'gene_based':            [-1.0, 50.0, 100.0, 250.0, 500.0],
    'module_based_archs4':   [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_gtex':     [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_recount2': [-1.0, 5.0, 10.0, 25.0, 50.0],
}
EXPECTED_METHODS = tuple(METHOD_THRESHOLDS)

In [4]:
DATA_DIR = here('data/drug_disease_associations')
display(DATA_DIR)
assert DATA_DIR.exists()

# Raw prediction HDF5 dirs for the four methods (NB06, NB07, NB08, NB09).
_PRED_BASE = here(
    'output/03_model_biology/00_archs4/02_drug_disease_associations')
PREDICTIONS_DIRS = {
    'gene_based':
        _PRED_BASE / '06_prediction_single_gene_based' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_archs4':
        _PRED_BASE / '07_prediction_module_based_archs4' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_gtex':
        _PRED_BASE / '08_prediction_module_based_gtex' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_recount2':
        _PRED_BASE / '09_prediction_module_based_recount2' / 'lincs' / 'predictions' / 'dotprod_neg',
}
# Map each method to the prediction notebook that produces it (for fail-loud msgs).
_METHOD_SOURCE_NB = {
    'gene_based':            'NB06 (06_prediction_single_gene_based)',
    'module_based_archs4':   'NB07 (07_prediction_module_based_archs4)',
    'module_based_gtex':     'NB08 (08_prediction_module_based_gtex)',
    'module_based_recount2': 'NB09 (09_prediction_module_based_recount2)',
}
for name, d in PREDICTIONS_DIRS.items():
    display((name, d))
    # Fail loud (do not silently score on partial data): the full 4-method grid
    # needs all of NB06-NB09 on disk.
    assert d.exists(), (
        f'{name} predictions missing -- run {_METHOD_SOURCE_NB[name]} first: {d}')

# The status-quo max-aggregate frame (produced by signif_test/00).
PAIRED_PKL = _PRED_BASE / 'signif_test' / 'predictions_paired.pkl'
assert PAIRED_PKL.exists(), f'run signif_test/00_aggregate_predictions first: {PAIRED_PKL}'

OUTPUT_DIR = _PRED_BASE / 'tissue_agg_test'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
display(OUTPUT_DIR)

PosixPath('/home/miltondp/projects/clamp/clamp-analyses/data/drug_disease_associations')

('gene_based',
 PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg'))

('module_based_archs4',
 PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/07_prediction_module_based_archs4/lincs/predictions/dotprod_neg'))

('module_based_gtex',
 PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/08_prediction_module_based_gtex/lincs/predictions/dotprod_neg'))

('module_based_recount2',
 PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/09_prediction_module_based_recount2/lincs/predictions/dotprod_neg'))

PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/tissue_agg_test')

# Load PharmacotherapyDB gold standard

In [5]:
gold_standard = pd.read_pickle(DATA_DIR / 'gold_standard.pkl')
display(gold_standard.shape)
display(gold_standard['true_class'].value_counts())

(998, 3)

true_class
1    755
0    243
Name: count, dtype: int64

# Helpers (copied verbatim from NB10 / signif_test/00)

In [6]:
def _get_tissue(data_value):
    """Extract tissue name from the metadata 'data' field."""
    prefix = 'spredixcan-mashr-zscores-'
    assert data_value.startswith(prefix), data_value
    tissue = data_value[len(prefix):]
    for suffix in (
        '-projection-archs4',
        '-projection-gtex',
        '-projection-recount2',
        '-projection',
        '-data',
    ):
        if tissue.endswith(suffix):
            return tissue[:-len(suffix)]
    raise ValueError(f'Cannot extract tissue from metadata data value: {data_value}')

# Load drug-disease predictions

Per file: rank `score` over the full DOID distribution, then inner-merge with the gold standard
(NB10 / signif_test order — rank first, then keep gold-standard pairs).

In [7]:
current_prediction_files = []
for d in PREDICTIONS_DIRS.values():
    current_prediction_files.extend(sorted(d.glob('*.h5')))
current_prediction_files.sort()
display(len(current_prediction_files))

980

In [8]:
# Load all prediction files, rank scores, merge with gold standard (NB10 logic).
predictions = []
skipped_files = []

for f in tqdm(current_prediction_files, ncols=100):
    metadata = pd.read_hdf(f, key='metadata')
    method_name = METHOD_RENAME.get(
        metadata['method'].values[0], metadata['method'].values[0])
    if method_name not in METHOD_THRESHOLDS:
        skipped_files.append((f.name, method_name))
        continue

    # Rank within the full DOID distribution, then keep gold-standard pairs.
    prediction_data = pd.read_hdf(f, key='prediction')
    prediction_data['score'] = prediction_data['score'].rank()
    prediction_data = pd.merge(
        prediction_data, gold_standard, on=['trait', 'drug'], how='inner')
    prediction_data['trait'] = prediction_data['trait'].astype('category')
    prediction_data['drug'] = prediction_data['drug'].astype('category')

    prediction_data = prediction_data.assign(method=method_name)
    prediction_data['method'] = pd.Categorical(
        prediction_data['method'], categories=EXPECTED_METHODS, ordered=True)
    prediction_data = prediction_data.assign(
        n_top_genes=metadata['n_top_genes'].values[0])

    data_value = metadata['data'].values[0]
    prediction_data = prediction_data.assign(data=data_value)
    prediction_data['data'] = prediction_data['data'].astype('category')
    prediction_data = prediction_data.assign(tissue=_get_tissue(data_value))

    predictions.append(prediction_data)

display(f'Skipped files: {len(skipped_files)}')
if skipped_files:
    display(skipped_files[:10])

  0%|                                                                       | 0/980 [00:00<?, ?it/s]

  0%|                                                               | 1/980 [00:00<03:09,  5.16it/s]

  0%|▏                                                              | 2/980 [00:00<02:56,  5.55it/s]

  0%|▏                                                              | 3/980 [00:00<02:50,  5.72it/s]

  0%|▎                                                              | 4/980 [00:00<02:48,  5.79it/s]

  1%|▎                                                              | 5/980 [00:00<02:46,  5.85it/s]

  1%|▍                                                              | 6/980 [00:01<02:45,  5.89it/s]

  1%|▍                                                              | 7/980 [00:01<02:44,  5.91it/s]

  1%|▌                                                              | 8/980 [00:01<02:43,  5.93it/s]

  1%|▌                                                              | 9/980 [00:01<02:43,  5.93it/s]

  1%|▋                                                             | 10/980 [00:01<02:43,  5.93it/s]

  1%|▋                                                             | 11/980 [00:01<02:43,  5.94it/s]

  1%|▊                                                             | 12/980 [00:02<02:43,  5.93it/s]

  1%|▊                                                             | 13/980 [00:02<02:42,  5.94it/s]

  1%|▉                                                             | 14/980 [00:02<02:42,  5.94it/s]

  2%|▉                                                             | 15/980 [00:02<02:42,  5.94it/s]

  2%|█                                                             | 16/980 [00:02<02:42,  5.93it/s]

  2%|█                                                             | 17/980 [00:02<02:42,  5.92it/s]

  2%|█▏                                                            | 18/980 [00:03<02:42,  5.91it/s]

  2%|█▏                                                            | 19/980 [00:03<02:42,  5.91it/s]

  2%|█▎                                                            | 20/980 [00:03<02:42,  5.92it/s]

  2%|█▎                                                            | 21/980 [00:03<02:42,  5.92it/s]

  2%|█▍                                                            | 22/980 [00:03<02:41,  5.92it/s]

  2%|█▍                                                            | 23/980 [00:03<02:42,  5.90it/s]

  2%|█▌                                                            | 24/980 [00:04<02:42,  5.89it/s]

  3%|█▌                                                            | 25/980 [00:04<02:42,  5.88it/s]

  3%|█▋                                                            | 26/980 [00:04<02:42,  5.88it/s]

  3%|█▋                                                            | 27/980 [00:04<02:41,  5.89it/s]

  3%|█▊                                                            | 28/980 [00:04<02:41,  5.90it/s]

  3%|█▊                                                            | 29/980 [00:04<02:41,  5.89it/s]

  3%|█▉                                                            | 30/980 [00:05<02:40,  5.93it/s]

  3%|█▉                                                            | 31/980 [00:05<02:38,  5.98it/s]

  3%|██                                                            | 32/980 [00:05<02:37,  6.02it/s]

  3%|██                                                            | 33/980 [00:05<02:36,  6.05it/s]

  3%|██▏                                                           | 34/980 [00:05<02:36,  6.06it/s]

  4%|██▏                                                           | 35/980 [00:05<02:35,  6.07it/s]

  4%|██▎                                                           | 36/980 [00:06<02:38,  5.96it/s]

  4%|██▎                                                           | 37/980 [00:06<02:40,  5.88it/s]

  4%|██▍                                                           | 38/980 [00:06<02:40,  5.86it/s]

  4%|██▍                                                           | 39/980 [00:06<02:41,  5.83it/s]

  4%|██▌                                                           | 40/980 [00:06<02:40,  5.85it/s]

  4%|██▌                                                           | 41/980 [00:06<02:39,  5.88it/s]

  4%|██▋                                                           | 42/980 [00:07<02:39,  5.90it/s]

  4%|██▋                                                           | 43/980 [00:07<02:38,  5.91it/s]

  4%|██▊                                                           | 44/980 [00:07<02:38,  5.91it/s]

  5%|██▊                                                           | 45/980 [00:07<02:38,  5.91it/s]

  5%|██▉                                                           | 46/980 [00:07<02:39,  5.87it/s]

  5%|██▉                                                           | 47/980 [00:07<02:39,  5.84it/s]

  5%|███                                                           | 48/980 [00:08<02:39,  5.86it/s]

  5%|███                                                           | 49/980 [00:08<02:38,  5.88it/s]

  5%|███▏                                                          | 50/980 [00:08<02:37,  5.89it/s]

  5%|███▏                                                          | 51/980 [00:08<02:37,  5.90it/s]

  5%|███▎                                                          | 52/980 [00:08<02:38,  5.87it/s]

  5%|███▎                                                          | 53/980 [00:08<02:39,  5.83it/s]

  6%|███▍                                                          | 54/980 [00:09<02:39,  5.81it/s]

  6%|███▍                                                          | 55/980 [00:09<02:38,  5.83it/s]

  6%|███▌                                                          | 56/980 [00:09<02:42,  5.69it/s]

  6%|███▌                                                          | 57/980 [00:09<02:44,  5.60it/s]

  6%|███▋                                                          | 58/980 [00:09<02:41,  5.69it/s]

  6%|███▋                                                          | 59/980 [00:10<02:39,  5.76it/s]

  6%|███▊                                                          | 60/980 [00:10<02:52,  5.34it/s]

  6%|███▊                                                          | 61/980 [00:10<02:48,  5.44it/s]

  6%|███▉                                                          | 62/980 [00:10<02:44,  5.57it/s]

  6%|███▉                                                          | 63/980 [00:10<02:41,  5.67it/s]

  7%|████                                                          | 64/980 [00:10<02:39,  5.74it/s]

  7%|████                                                          | 65/980 [00:11<02:38,  5.77it/s]

  7%|████▏                                                         | 66/980 [00:11<02:37,  5.80it/s]

  7%|████▏                                                         | 67/980 [00:11<02:36,  5.83it/s]

  7%|████▎                                                         | 68/980 [00:11<02:37,  5.81it/s]

  7%|████▎                                                         | 69/980 [00:11<02:36,  5.81it/s]

  7%|████▍                                                         | 70/980 [00:11<02:39,  5.71it/s]

  7%|████▍                                                         | 71/980 [00:12<02:38,  5.72it/s]

  7%|████▌                                                         | 72/980 [00:12<02:37,  5.77it/s]

  7%|████▌                                                         | 73/980 [00:12<02:37,  5.78it/s]

  8%|████▋                                                         | 74/980 [00:12<02:36,  5.80it/s]

  8%|████▋                                                         | 75/980 [00:12<02:35,  5.83it/s]

  8%|████▊                                                         | 76/980 [00:13<02:34,  5.84it/s]

  8%|████▊                                                         | 77/980 [00:13<02:36,  5.77it/s]

  8%|████▉                                                         | 78/980 [00:13<02:36,  5.77it/s]

  8%|████▉                                                         | 79/980 [00:13<02:35,  5.80it/s]

  8%|█████                                                         | 80/980 [00:13<02:34,  5.82it/s]

  8%|█████                                                         | 81/980 [00:13<02:34,  5.84it/s]

  8%|█████▏                                                        | 82/980 [00:14<02:33,  5.85it/s]

  8%|█████▎                                                        | 83/980 [00:14<02:32,  5.87it/s]

  9%|█████▎                                                        | 84/980 [00:14<02:32,  5.88it/s]

  9%|█████▍                                                        | 85/980 [00:14<02:32,  5.86it/s]

  9%|█████▍                                                        | 86/980 [00:14<02:32,  5.86it/s]

  9%|█████▌                                                        | 87/980 [00:14<02:32,  5.87it/s]

  9%|█████▌                                                        | 88/980 [00:15<02:32,  5.87it/s]

  9%|█████▋                                                        | 89/980 [00:15<02:31,  5.88it/s]

  9%|█████▋                                                        | 90/980 [00:15<02:31,  5.87it/s]

  9%|█████▊                                                        | 91/980 [00:15<02:31,  5.85it/s]

  9%|█████▊                                                        | 92/980 [00:15<02:30,  5.89it/s]

  9%|█████▉                                                        | 93/980 [00:15<02:30,  5.91it/s]

 10%|█████▉                                                        | 94/980 [00:16<02:29,  5.94it/s]

 10%|██████                                                        | 95/980 [00:16<02:28,  5.95it/s]

 10%|██████                                                        | 96/980 [00:16<02:28,  5.95it/s]

 10%|██████▏                                                       | 97/980 [00:16<02:28,  5.95it/s]

 10%|██████▏                                                       | 98/980 [00:16<02:28,  5.94it/s]

 10%|██████▎                                                       | 99/980 [00:16<02:28,  5.95it/s]

 10%|██████▏                                                      | 100/980 [00:17<02:27,  5.96it/s]

 10%|██████▎                                                      | 101/980 [00:17<02:27,  5.95it/s]

 10%|██████▎                                                      | 102/980 [00:17<02:28,  5.89it/s]

 11%|██████▍                                                      | 103/980 [00:17<02:28,  5.91it/s]

 11%|██████▍                                                      | 104/980 [00:17<02:27,  5.93it/s]

 11%|██████▌                                                      | 105/980 [00:17<02:28,  5.89it/s]

 11%|██████▌                                                      | 106/980 [00:18<02:28,  5.87it/s]

 11%|██████▋                                                      | 107/980 [00:18<02:27,  5.90it/s]

 11%|██████▋                                                      | 108/980 [00:18<02:27,  5.92it/s]

 11%|██████▊                                                      | 109/980 [00:18<02:27,  5.92it/s]

 11%|██████▊                                                      | 110/980 [00:18<02:26,  5.93it/s]

 11%|██████▉                                                      | 111/980 [00:18<02:26,  5.94it/s]

 11%|██████▉                                                      | 112/980 [00:19<02:26,  5.94it/s]

 12%|███████                                                      | 113/980 [00:19<02:25,  5.95it/s]

 12%|███████                                                      | 114/980 [00:19<02:25,  5.95it/s]

 12%|███████▏                                                     | 115/980 [00:19<02:25,  5.95it/s]

 12%|███████▏                                                     | 116/980 [00:19<02:24,  5.96it/s]

 12%|███████▎                                                     | 117/980 [00:19<02:24,  5.95it/s]

 12%|███████▎                                                     | 118/980 [00:20<02:24,  5.95it/s]

 12%|███████▍                                                     | 119/980 [00:20<02:24,  5.95it/s]

 12%|███████▍                                                     | 120/980 [00:20<02:24,  5.94it/s]

 12%|███████▌                                                     | 121/980 [00:20<02:24,  5.93it/s]

 12%|███████▌                                                     | 122/980 [00:20<02:24,  5.92it/s]

 13%|███████▋                                                     | 123/980 [00:20<02:27,  5.80it/s]

 13%|███████▋                                                     | 124/980 [00:21<02:27,  5.81it/s]

 13%|███████▊                                                     | 125/980 [00:21<02:26,  5.82it/s]

 13%|███████▊                                                     | 126/980 [00:21<02:26,  5.84it/s]

 13%|███████▉                                                     | 127/980 [00:21<02:25,  5.87it/s]

 13%|███████▉                                                     | 128/980 [00:21<02:24,  5.89it/s]

 13%|████████                                                     | 129/980 [00:21<02:24,  5.91it/s]

 13%|████████                                                     | 130/980 [00:22<02:23,  5.92it/s]

 13%|████████▏                                                    | 131/980 [00:22<02:23,  5.93it/s]

 13%|████████▏                                                    | 132/980 [00:22<02:23,  5.91it/s]

 14%|████████▎                                                    | 133/980 [00:22<02:23,  5.90it/s]

 14%|████████▎                                                    | 134/980 [00:22<02:23,  5.88it/s]

 14%|████████▍                                                    | 135/980 [00:23<02:23,  5.89it/s]

 14%|████████▍                                                    | 136/980 [00:23<02:22,  5.91it/s]

 14%|████████▌                                                    | 137/980 [00:23<02:23,  5.88it/s]

 14%|████████▌                                                    | 138/980 [00:23<02:23,  5.88it/s]

 14%|████████▋                                                    | 139/980 [00:23<02:23,  5.88it/s]

 14%|████████▋                                                    | 140/980 [00:23<02:22,  5.90it/s]

 14%|████████▊                                                    | 141/980 [00:24<02:22,  5.91it/s]

 14%|████████▊                                                    | 142/980 [00:24<02:21,  5.91it/s]

 15%|████████▉                                                    | 143/980 [00:24<02:21,  5.91it/s]

 15%|████████▉                                                    | 144/980 [00:24<02:21,  5.89it/s]

 15%|█████████                                                    | 145/980 [00:24<02:22,  5.87it/s]

 15%|█████████                                                    | 146/980 [00:24<02:22,  5.86it/s]

 15%|█████████▏                                                   | 147/980 [00:25<02:21,  5.87it/s]

 15%|█████████▏                                                   | 148/980 [00:25<02:21,  5.88it/s]

 15%|█████████▎                                                   | 149/980 [00:25<02:21,  5.88it/s]

 15%|█████████▎                                                   | 150/980 [00:25<02:20,  5.89it/s]

 15%|█████████▍                                                   | 151/980 [00:25<02:20,  5.89it/s]

 16%|█████████▍                                                   | 152/980 [00:25<02:20,  5.89it/s]

 16%|█████████▌                                                   | 153/980 [00:26<02:20,  5.89it/s]

 16%|█████████▌                                                   | 154/980 [00:26<02:20,  5.88it/s]

 16%|█████████▋                                                   | 155/980 [00:26<02:20,  5.88it/s]

 16%|█████████▋                                                   | 156/980 [00:26<02:20,  5.88it/s]

 16%|█████████▊                                                   | 157/980 [00:26<02:19,  5.89it/s]

 16%|█████████▊                                                   | 158/980 [00:26<02:19,  5.88it/s]

 16%|█████████▉                                                   | 159/980 [00:27<02:19,  5.89it/s]

 16%|█████████▉                                                   | 160/980 [00:27<02:19,  5.89it/s]

 16%|██████████                                                   | 161/980 [00:27<02:19,  5.89it/s]

 17%|██████████                                                   | 162/980 [00:27<02:18,  5.89it/s]

 17%|██████████▏                                                  | 163/980 [00:27<02:18,  5.90it/s]

 17%|██████████▏                                                  | 164/980 [00:27<02:18,  5.91it/s]

 17%|██████████▎                                                  | 165/980 [00:28<02:17,  5.91it/s]

 17%|██████████▎                                                  | 166/980 [00:28<02:17,  5.92it/s]

 17%|██████████▍                                                  | 167/980 [00:28<02:17,  5.91it/s]

 17%|██████████▍                                                  | 168/980 [00:28<02:17,  5.91it/s]

 17%|██████████▌                                                  | 169/980 [00:28<02:17,  5.90it/s]

 17%|██████████▌                                                  | 170/980 [00:28<02:17,  5.89it/s]

 17%|██████████▋                                                  | 171/980 [00:29<02:17,  5.89it/s]

 18%|██████████▋                                                  | 172/980 [00:29<02:17,  5.89it/s]

 18%|██████████▊                                                  | 173/980 [00:29<02:17,  5.89it/s]

 18%|██████████▊                                                  | 174/980 [00:29<02:16,  5.89it/s]

 18%|██████████▉                                                  | 175/980 [00:29<02:16,  5.88it/s]

 18%|██████████▉                                                  | 176/980 [00:29<02:16,  5.88it/s]

 18%|███████████                                                  | 177/980 [00:30<02:16,  5.89it/s]

 18%|███████████                                                  | 178/980 [00:30<02:15,  5.90it/s]

 18%|███████████▏                                                 | 179/980 [00:30<02:15,  5.91it/s]

 18%|███████████▏                                                 | 180/980 [00:30<02:15,  5.89it/s]

 18%|███████████▎                                                 | 181/980 [00:30<02:15,  5.88it/s]

 19%|███████████▎                                                 | 182/980 [00:30<02:16,  5.85it/s]

 19%|███████████▍                                                 | 183/980 [00:31<02:16,  5.84it/s]

 19%|███████████▍                                                 | 184/980 [00:31<02:15,  5.86it/s]

 19%|███████████▌                                                 | 185/980 [00:31<02:15,  5.85it/s]

 19%|███████████▌                                                 | 186/980 [00:31<02:15,  5.86it/s]

 19%|███████████▋                                                 | 187/980 [00:31<02:17,  5.78it/s]

 19%|███████████▋                                                 | 188/980 [00:32<02:18,  5.74it/s]

 19%|███████████▊                                                 | 189/980 [00:32<02:17,  5.77it/s]

 19%|███████████▊                                                 | 190/980 [00:32<02:17,  5.73it/s]

 19%|███████████▉                                                 | 191/980 [00:32<02:16,  5.79it/s]

 20%|███████████▉                                                 | 192/980 [00:32<02:15,  5.83it/s]

 20%|████████████                                                 | 193/980 [00:32<02:14,  5.85it/s]

 20%|████████████                                                 | 194/980 [00:33<02:13,  5.87it/s]

 20%|████████████▏                                                | 195/980 [00:33<02:13,  5.89it/s]

 20%|████████████▏                                                | 196/980 [00:33<02:12,  5.91it/s]

 20%|████████████▎                                                | 197/980 [00:33<02:12,  5.91it/s]

 20%|████████████▎                                                | 198/980 [00:33<02:12,  5.92it/s]

 20%|████████████▍                                                | 199/980 [00:33<02:11,  5.93it/s]

 20%|████████████▍                                                | 200/980 [00:34<02:11,  5.94it/s]

 21%|████████████▌                                                | 201/980 [00:34<02:11,  5.95it/s]

 21%|████████████▌                                                | 202/980 [00:34<02:10,  5.95it/s]

 21%|████████████▋                                                | 203/980 [00:34<02:10,  5.94it/s]

 21%|████████████▋                                                | 204/980 [00:34<02:10,  5.93it/s]

 21%|████████████▊                                                | 205/980 [00:34<02:10,  5.94it/s]

 21%|████████████▊                                                | 206/980 [00:35<02:10,  5.93it/s]

 21%|████████████▉                                                | 207/980 [00:35<02:10,  5.93it/s]

 21%|████████████▉                                                | 208/980 [00:35<02:10,  5.91it/s]

 21%|█████████████                                                | 209/980 [00:35<02:10,  5.92it/s]

 21%|█████████████                                                | 210/980 [00:35<02:11,  5.88it/s]

 22%|█████████████▏                                               | 211/980 [00:35<02:12,  5.80it/s]

 22%|█████████████▏                                               | 212/980 [00:36<02:11,  5.84it/s]

 22%|█████████████▎                                               | 213/980 [00:36<02:10,  5.86it/s]

 22%|█████████████▎                                               | 214/980 [00:36<02:10,  5.88it/s]

 22%|█████████████▍                                               | 215/980 [00:36<02:09,  5.90it/s]

 22%|█████████████▍                                               | 216/980 [00:36<02:09,  5.91it/s]

 22%|█████████████▌                                               | 217/980 [00:36<02:08,  5.92it/s]

 22%|█████████████▌                                               | 218/980 [00:37<02:08,  5.92it/s]

 22%|█████████████▋                                               | 219/980 [00:37<02:08,  5.93it/s]

 22%|█████████████▋                                               | 220/980 [00:37<02:09,  5.89it/s]

 23%|█████████████▊                                               | 221/980 [00:37<02:08,  5.89it/s]

 23%|█████████████▊                                               | 222/980 [00:37<02:08,  5.89it/s]

 23%|█████████████▉                                               | 223/980 [00:37<02:08,  5.89it/s]

 23%|█████████████▉                                               | 224/980 [00:38<02:09,  5.85it/s]

 23%|██████████████                                               | 225/980 [00:38<02:10,  5.80it/s]

 23%|██████████████                                               | 226/980 [00:38<02:09,  5.80it/s]

 23%|██████████████▏                                              | 227/980 [00:38<02:09,  5.83it/s]

 23%|██████████████▏                                              | 228/980 [00:38<02:08,  5.84it/s]

 23%|██████████████▎                                              | 229/980 [00:38<02:07,  5.89it/s]

 23%|██████████████▎                                              | 230/980 [00:39<02:07,  5.90it/s]

 24%|██████████████▍                                              | 231/980 [00:39<02:06,  5.94it/s]

 24%|██████████████▍                                              | 232/980 [00:39<02:05,  5.96it/s]

 24%|██████████████▌                                              | 233/980 [00:39<02:04,  5.99it/s]

 24%|██████████████▌                                              | 234/980 [00:39<02:04,  6.00it/s]

 24%|██████████████▋                                              | 235/980 [00:39<02:05,  5.95it/s]

 24%|██████████████▋                                              | 236/980 [00:40<02:04,  5.95it/s]

 24%|██████████████▊                                              | 237/980 [00:40<02:04,  5.96it/s]

 24%|██████████████▊                                              | 238/980 [00:40<02:04,  5.96it/s]

 24%|██████████████▉                                              | 239/980 [00:40<02:05,  5.91it/s]

 24%|██████████████▉                                              | 240/980 [00:40<02:05,  5.90it/s]

 25%|███████████████                                              | 241/980 [00:41<02:05,  5.87it/s]

 25%|███████████████                                              | 242/980 [00:41<02:05,  5.87it/s]

 25%|███████████████▏                                             | 243/980 [00:41<02:05,  5.89it/s]

 25%|███████████████▏                                             | 244/980 [00:41<02:04,  5.90it/s]

 25%|███████████████▎                                             | 245/980 [00:41<02:04,  5.89it/s]

 25%|███████████████▎                                             | 246/980 [00:41<02:04,  5.90it/s]

 25%|███████████████▎                                             | 247/980 [00:42<02:03,  5.91it/s]

 25%|███████████████▍                                             | 248/980 [00:42<02:03,  5.93it/s]

 25%|███████████████▍                                             | 249/980 [00:42<02:03,  5.93it/s]

 26%|███████████████▌                                             | 250/980 [00:42<02:02,  5.94it/s]

 26%|███████████████▌                                             | 251/980 [00:42<02:02,  5.93it/s]

 26%|███████████████▋                                             | 252/980 [00:42<02:02,  5.95it/s]

 26%|███████████████▋                                             | 253/980 [00:43<02:02,  5.95it/s]

 26%|███████████████▊                                             | 254/980 [00:43<02:02,  5.94it/s]

 26%|███████████████▊                                             | 255/980 [00:43<02:02,  5.92it/s]

 26%|███████████████▉                                             | 256/980 [00:43<02:02,  5.92it/s]

 26%|███████████████▉                                             | 257/980 [00:43<02:01,  5.94it/s]

 26%|████████████████                                             | 258/980 [00:43<02:01,  5.94it/s]

 26%|████████████████                                             | 259/980 [00:44<02:01,  5.95it/s]

 27%|████████████████▏                                            | 260/980 [00:44<02:00,  5.96it/s]

 27%|████████████████▏                                            | 261/980 [00:44<02:00,  5.95it/s]

 27%|████████████████▎                                            | 262/980 [00:44<02:00,  5.94it/s]

 27%|████████████████▎                                            | 263/980 [00:44<02:00,  5.93it/s]

 27%|████████████████▍                                            | 264/980 [00:44<02:00,  5.94it/s]

 27%|████████████████▍                                            | 265/980 [00:45<02:00,  5.93it/s]

 27%|████████████████▌                                            | 266/980 [00:45<02:00,  5.91it/s]

 27%|████████████████▌                                            | 267/980 [00:45<02:00,  5.90it/s]

 27%|████████████████▋                                            | 268/980 [00:45<02:00,  5.89it/s]

 27%|████████████████▋                                            | 269/980 [00:45<02:00,  5.89it/s]

 28%|████████████████▊                                            | 270/980 [00:45<02:00,  5.90it/s]

 28%|████████████████▊                                            | 271/980 [00:46<02:00,  5.88it/s]

 28%|████████████████▉                                            | 272/980 [00:46<02:01,  5.84it/s]

 28%|████████████████▉                                            | 273/980 [00:46<02:00,  5.86it/s]

 28%|█████████████████                                            | 274/980 [00:46<02:00,  5.84it/s]

 28%|█████████████████                                            | 275/980 [00:46<02:01,  5.81it/s]

 28%|█████████████████▏                                           | 276/980 [00:46<02:01,  5.81it/s]

 28%|█████████████████▏                                           | 277/980 [00:47<02:14,  5.22it/s]

 28%|█████████████████▎                                           | 278/980 [00:47<02:10,  5.38it/s]

 28%|█████████████████▎                                           | 279/980 [00:47<02:07,  5.50it/s]

 29%|█████████████████▍                                           | 280/980 [00:47<02:05,  5.59it/s]

 29%|█████████████████▍                                           | 281/980 [00:47<02:03,  5.65it/s]

 29%|█████████████████▌                                           | 282/980 [00:48<02:03,  5.64it/s]

 29%|█████████████████▌                                           | 283/980 [00:48<02:03,  5.66it/s]

 29%|█████████████████▋                                           | 284/980 [00:48<02:02,  5.66it/s]

 29%|█████████████████▋                                           | 285/980 [00:48<02:02,  5.69it/s]

 29%|█████████████████▊                                           | 286/980 [00:48<02:01,  5.72it/s]

 29%|█████████████████▊                                           | 287/980 [00:48<02:00,  5.74it/s]

 29%|█████████████████▉                                           | 288/980 [00:49<02:00,  5.77it/s]

 29%|█████████████████▉                                           | 289/980 [00:49<01:59,  5.79it/s]

 30%|██████████████████                                           | 290/980 [00:49<01:59,  5.79it/s]

 30%|██████████████████                                           | 291/980 [00:49<01:59,  5.79it/s]

 30%|██████████████████▏                                          | 292/980 [00:49<01:58,  5.81it/s]

 30%|██████████████████▏                                          | 293/980 [00:49<01:57,  5.84it/s]

 30%|██████████████████▎                                          | 294/980 [00:50<01:56,  5.88it/s]

 30%|██████████████████▎                                          | 295/980 [00:50<01:56,  5.86it/s]

 30%|██████████████████▍                                          | 296/980 [00:50<01:55,  5.91it/s]

 30%|██████████████████▍                                          | 297/980 [00:50<01:55,  5.94it/s]

 30%|██████████████████▌                                          | 298/980 [00:50<01:55,  5.92it/s]

 31%|██████████████████▌                                          | 299/980 [00:50<01:55,  5.90it/s]

 31%|██████████████████▋                                          | 300/980 [00:51<01:55,  5.91it/s]

 31%|██████████████████▋                                          | 301/980 [00:51<01:55,  5.89it/s]

 31%|██████████████████▊                                          | 302/980 [00:51<01:55,  5.88it/s]

 31%|██████████████████▊                                          | 303/980 [00:51<01:55,  5.87it/s]

 31%|██████████████████▉                                          | 304/980 [00:51<01:55,  5.88it/s]

 31%|██████████████████▉                                          | 305/980 [00:51<01:54,  5.89it/s]

 31%|███████████████████                                          | 306/980 [00:52<01:54,  5.89it/s]

 31%|███████████████████                                          | 307/980 [00:52<01:54,  5.89it/s]

 31%|███████████████████▏                                         | 308/980 [00:52<01:54,  5.89it/s]

 32%|███████████████████▏                                         | 309/980 [00:52<01:53,  5.89it/s]

 32%|███████████████████▎                                         | 310/980 [00:52<01:53,  5.89it/s]

 32%|███████████████████▎                                         | 311/980 [00:52<01:53,  5.88it/s]

 32%|███████████████████▍                                         | 312/980 [00:53<01:53,  5.88it/s]

 32%|███████████████████▍                                         | 313/980 [00:53<01:53,  5.88it/s]

 32%|███████████████████▌                                         | 314/980 [00:53<01:53,  5.87it/s]

 32%|███████████████████▌                                         | 315/980 [00:53<01:53,  5.87it/s]

 32%|███████████████████▋                                         | 316/980 [00:53<01:52,  5.88it/s]

 32%|███████████████████▋                                         | 317/980 [00:54<01:53,  5.86it/s]

 32%|███████████████████▊                                         | 318/980 [00:54<01:52,  5.87it/s]

 33%|███████████████████▊                                         | 319/980 [00:54<01:52,  5.89it/s]

 33%|███████████████████▉                                         | 320/980 [00:54<01:52,  5.88it/s]

 33%|███████████████████▉                                         | 321/980 [00:54<01:52,  5.88it/s]

 33%|████████████████████                                         | 322/980 [00:54<01:52,  5.87it/s]

 33%|████████████████████                                         | 323/980 [00:55<01:53,  5.77it/s]

 33%|████████████████████▏                                        | 324/980 [00:55<01:54,  5.75it/s]

 33%|████████████████████▏                                        | 325/980 [00:55<01:53,  5.77it/s]

 33%|████████████████████▎                                        | 326/980 [00:55<01:52,  5.81it/s]

 33%|████████████████████▎                                        | 327/980 [00:55<01:51,  5.84it/s]

 33%|████████████████████▍                                        | 328/980 [00:55<01:51,  5.86it/s]

 34%|████████████████████▍                                        | 329/980 [00:56<01:50,  5.88it/s]

 34%|████████████████████▌                                        | 330/980 [00:56<01:50,  5.89it/s]

 34%|████████████████████▌                                        | 331/980 [00:56<01:50,  5.89it/s]

 34%|████████████████████▋                                        | 332/980 [00:56<01:49,  5.91it/s]

 34%|████████████████████▋                                        | 333/980 [00:56<01:49,  5.91it/s]

 34%|████████████████████▊                                        | 334/980 [00:56<01:49,  5.92it/s]

 34%|████████████████████▊                                        | 335/980 [00:57<01:48,  5.94it/s]

 34%|████████████████████▉                                        | 336/980 [00:57<01:48,  5.96it/s]

 34%|████████████████████▉                                        | 337/980 [00:57<01:47,  5.97it/s]

 34%|█████████████████████                                        | 338/980 [00:57<01:49,  5.85it/s]

 35%|█████████████████████                                        | 339/980 [00:57<01:50,  5.79it/s]

 35%|█████████████████████▏                                       | 340/980 [00:57<01:50,  5.80it/s]

 35%|█████████████████████▏                                       | 341/980 [00:58<01:49,  5.82it/s]

 35%|█████████████████████▎                                       | 342/980 [00:58<01:49,  5.81it/s]

 35%|█████████████████████▎                                       | 343/980 [00:58<01:49,  5.81it/s]

 35%|█████████████████████▍                                       | 344/980 [00:58<01:48,  5.84it/s]

 35%|█████████████████████▍                                       | 345/980 [00:58<01:48,  5.86it/s]

 35%|█████████████████████▌                                       | 346/980 [00:58<01:47,  5.87it/s]

 35%|█████████████████████▌                                       | 347/980 [00:59<01:47,  5.87it/s]

 36%|█████████████████████▋                                       | 348/980 [00:59<01:47,  5.89it/s]

 36%|█████████████████████▋                                       | 349/980 [00:59<01:47,  5.88it/s]

 36%|█████████████████████▊                                       | 350/980 [00:59<01:47,  5.86it/s]

 36%|█████████████████████▊                                       | 351/980 [00:59<01:47,  5.86it/s]

 36%|█████████████████████▉                                       | 352/980 [00:59<01:47,  5.86it/s]

 36%|█████████████████████▉                                       | 353/980 [01:00<01:47,  5.86it/s]

 36%|██████████████████████                                       | 354/980 [01:00<01:46,  5.87it/s]

 36%|██████████████████████                                       | 355/980 [01:00<01:46,  5.86it/s]

 36%|██████████████████████▏                                      | 356/980 [01:00<01:46,  5.85it/s]

 36%|██████████████████████▏                                      | 357/980 [01:00<01:46,  5.86it/s]

 37%|██████████████████████▎                                      | 358/980 [01:01<01:46,  5.87it/s]

 37%|██████████████████████▎                                      | 359/980 [01:01<01:46,  5.86it/s]

 37%|██████████████████████▍                                      | 360/980 [01:01<01:46,  5.84it/s]

 37%|██████████████████████▍                                      | 361/980 [01:01<01:45,  5.84it/s]

 37%|██████████████████████▌                                      | 362/980 [01:01<01:46,  5.82it/s]

 37%|██████████████████████▌                                      | 363/980 [01:01<01:45,  5.83it/s]

 37%|██████████████████████▋                                      | 364/980 [01:02<01:46,  5.80it/s]

 37%|██████████████████████▋                                      | 365/980 [01:02<01:45,  5.82it/s]

 37%|██████████████████████▊                                      | 366/980 [01:02<01:45,  5.84it/s]

 37%|██████████████████████▊                                      | 367/980 [01:02<01:45,  5.83it/s]

 38%|██████████████████████▉                                      | 368/980 [01:02<01:44,  5.85it/s]

 38%|██████████████████████▉                                      | 369/980 [01:02<01:44,  5.83it/s]

 38%|███████████████████████                                      | 370/980 [01:03<01:44,  5.82it/s]

 38%|███████████████████████                                      | 371/980 [01:03<01:44,  5.83it/s]

 38%|███████████████████████▏                                     | 372/980 [01:03<01:44,  5.84it/s]

 38%|███████████████████████▏                                     | 373/980 [01:03<01:43,  5.85it/s]

 38%|███████████████████████▎                                     | 374/980 [01:03<01:43,  5.83it/s]

 38%|███████████████████████▎                                     | 375/980 [01:03<01:43,  5.83it/s]

 38%|███████████████████████▍                                     | 376/980 [01:04<01:42,  5.87it/s]

 38%|███████████████████████▍                                     | 377/980 [01:04<01:42,  5.88it/s]

 39%|███████████████████████▌                                     | 378/980 [01:04<01:42,  5.88it/s]

 39%|███████████████████████▌                                     | 379/980 [01:04<01:42,  5.89it/s]

 39%|███████████████████████▋                                     | 380/980 [01:04<01:41,  5.91it/s]

 39%|███████████████████████▋                                     | 381/980 [01:04<01:41,  5.91it/s]

 39%|███████████████████████▊                                     | 382/980 [01:05<01:41,  5.92it/s]

 39%|███████████████████████▊                                     | 383/980 [01:05<01:40,  5.93it/s]

 39%|███████████████████████▉                                     | 384/980 [01:05<01:41,  5.90it/s]

 39%|███████████████████████▉                                     | 385/980 [01:05<01:41,  5.86it/s]

 39%|████████████████████████                                     | 386/980 [01:05<01:41,  5.86it/s]

 39%|████████████████████████                                     | 387/980 [01:05<01:41,  5.83it/s]

 40%|████████████████████████▏                                    | 388/980 [01:06<01:41,  5.82it/s]

 40%|████████████████████████▏                                    | 389/980 [01:06<01:42,  5.79it/s]

 40%|████████████████████████▎                                    | 390/980 [01:06<01:42,  5.76it/s]

 40%|████████████████████████▎                                    | 391/980 [01:06<01:41,  5.80it/s]

 40%|████████████████████████▍                                    | 392/980 [01:06<01:40,  5.83it/s]

 40%|████████████████████████▍                                    | 393/980 [01:07<01:40,  5.85it/s]

 40%|████████████████████████▌                                    | 394/980 [01:07<01:39,  5.88it/s]

 40%|████████████████████████▌                                    | 395/980 [01:07<01:39,  5.88it/s]

 40%|████████████████████████▋                                    | 396/980 [01:07<01:41,  5.77it/s]

 41%|████████████████████████▋                                    | 397/980 [01:07<01:41,  5.75it/s]

 41%|████████████████████████▊                                    | 398/980 [01:07<01:41,  5.76it/s]

 41%|████████████████████████▊                                    | 399/980 [01:08<01:40,  5.79it/s]

 41%|████████████████████████▉                                    | 400/980 [01:08<01:39,  5.82it/s]

 41%|████████████████████████▉                                    | 401/980 [01:08<01:39,  5.82it/s]

 41%|█████████████████████████                                    | 402/980 [01:08<01:39,  5.83it/s]

 41%|█████████████████████████                                    | 403/980 [01:08<01:38,  5.84it/s]

 41%|█████████████████████████▏                                   | 404/980 [01:08<01:39,  5.81it/s]

 41%|█████████████████████████▏                                   | 405/980 [01:09<01:39,  5.75it/s]

 41%|█████████████████████████▎                                   | 406/980 [01:09<01:40,  5.73it/s]

 42%|█████████████████████████▎                                   | 407/980 [01:09<01:40,  5.71it/s]

 42%|█████████████████████████▍                                   | 408/980 [01:09<01:39,  5.76it/s]

 42%|█████████████████████████▍                                   | 409/980 [01:09<01:38,  5.81it/s]

 42%|█████████████████████████▌                                   | 410/980 [01:09<01:37,  5.84it/s]

 42%|█████████████████████████▌                                   | 411/980 [01:10<01:37,  5.83it/s]

 42%|█████████████████████████▋                                   | 412/980 [01:10<01:37,  5.85it/s]

 42%|█████████████████████████▋                                   | 413/980 [01:10<01:36,  5.86it/s]

 42%|█████████████████████████▊                                   | 414/980 [01:10<01:36,  5.87it/s]

 42%|█████████████████████████▊                                   | 415/980 [01:10<01:36,  5.88it/s]

 42%|█████████████████████████▉                                   | 416/980 [01:10<01:36,  5.87it/s]

 43%|█████████████████████████▉                                   | 417/980 [01:11<01:35,  5.87it/s]

 43%|██████████████████████████                                   | 418/980 [01:11<01:35,  5.88it/s]

 43%|██████████████████████████                                   | 419/980 [01:11<01:35,  5.89it/s]

 43%|██████████████████████████▏                                  | 420/980 [01:11<01:34,  5.90it/s]

 43%|██████████████████████████▏                                  | 421/980 [01:11<01:34,  5.90it/s]

 43%|██████████████████████████▎                                  | 422/980 [01:11<01:35,  5.82it/s]

 43%|██████████████████████████▎                                  | 423/980 [01:12<01:35,  5.83it/s]

 43%|██████████████████████████▍                                  | 424/980 [01:12<01:35,  5.84it/s]

 43%|██████████████████████████▍                                  | 425/980 [01:12<01:34,  5.85it/s]

 43%|██████████████████████████▌                                  | 426/980 [01:12<01:34,  5.86it/s]

 44%|██████████████████████████▌                                  | 427/980 [01:12<01:34,  5.87it/s]

 44%|██████████████████████████▋                                  | 428/980 [01:13<01:34,  5.85it/s]

 44%|██████████████████████████▋                                  | 429/980 [01:13<01:34,  5.81it/s]

 44%|██████████████████████████▊                                  | 430/980 [01:13<01:34,  5.84it/s]

 44%|██████████████████████████▊                                  | 431/980 [01:13<01:33,  5.87it/s]

 44%|██████████████████████████▉                                  | 432/980 [01:13<01:33,  5.89it/s]

 44%|██████████████████████████▉                                  | 433/980 [01:13<01:32,  5.90it/s]

 44%|███████████████████████████                                  | 434/980 [01:14<01:32,  5.91it/s]

 44%|███████████████████████████                                  | 435/980 [01:14<01:32,  5.88it/s]

 44%|███████████████████████████▏                                 | 436/980 [01:14<01:32,  5.89it/s]

 45%|███████████████████████████▏                                 | 437/980 [01:14<01:31,  5.91it/s]

 45%|███████████████████████████▎                                 | 438/980 [01:14<01:31,  5.92it/s]

 45%|███████████████████████████▎                                 | 439/980 [01:14<01:31,  5.92it/s]

 45%|███████████████████████████▍                                 | 440/980 [01:15<01:32,  5.85it/s]

 45%|███████████████████████████▍                                 | 441/980 [01:15<01:32,  5.83it/s]

 45%|███████████████████████████▌                                 | 442/980 [01:15<01:32,  5.83it/s]

 45%|███████████████████████████▌                                 | 443/980 [01:15<01:32,  5.82it/s]

 45%|███████████████████████████▋                                 | 444/980 [01:15<01:31,  5.83it/s]

 45%|███████████████████████████▋                                 | 445/980 [01:15<01:31,  5.83it/s]

 46%|███████████████████████████▊                                 | 446/980 [01:16<01:31,  5.83it/s]

 46%|███████████████████████████▊                                 | 447/980 [01:16<01:31,  5.82it/s]

 46%|███████████████████████████▉                                 | 448/980 [01:16<01:31,  5.83it/s]

 46%|███████████████████████████▉                                 | 449/980 [01:16<01:31,  5.83it/s]

 46%|████████████████████████████                                 | 450/980 [01:16<01:30,  5.85it/s]

 46%|████████████████████████████                                 | 451/980 [01:16<01:30,  5.85it/s]

 46%|████████████████████████████▏                                | 452/980 [01:17<01:30,  5.84it/s]

 46%|████████████████████████████▏                                | 453/980 [01:17<01:30,  5.85it/s]

 46%|████████████████████████████▎                                | 454/980 [01:17<01:29,  5.86it/s]

 46%|████████████████████████████▎                                | 455/980 [01:17<01:29,  5.87it/s]

 47%|████████████████████████████▍                                | 456/980 [01:17<01:29,  5.88it/s]

 47%|████████████████████████████▍                                | 457/980 [01:17<01:28,  5.90it/s]

 47%|████████████████████████████▌                                | 458/980 [01:18<01:28,  5.90it/s]

 47%|████████████████████████████▌                                | 459/980 [01:18<01:28,  5.87it/s]

 47%|████████████████████████████▋                                | 460/980 [01:18<01:28,  5.86it/s]

 47%|████████████████████████████▋                                | 461/980 [01:18<01:28,  5.86it/s]

 47%|████████████████████████████▊                                | 462/980 [01:18<01:28,  5.85it/s]

 47%|████████████████████████████▊                                | 463/980 [01:18<01:28,  5.87it/s]

 47%|████████████████████████████▉                                | 464/980 [01:19<01:27,  5.88it/s]

 47%|████████████████████████████▉                                | 465/980 [01:19<01:27,  5.89it/s]

 48%|█████████████████████████████                                | 466/980 [01:19<01:27,  5.88it/s]

 48%|█████████████████████████████                                | 467/980 [01:19<01:27,  5.89it/s]

 48%|█████████████████████████████▏                               | 468/980 [01:19<01:27,  5.88it/s]

 48%|█████████████████████████████▏                               | 469/980 [01:19<01:26,  5.89it/s]

 48%|█████████████████████████████▎                               | 470/980 [01:20<01:26,  5.89it/s]

 48%|█████████████████████████████▎                               | 471/980 [01:20<01:26,  5.87it/s]

 48%|█████████████████████████████▍                               | 472/980 [01:20<01:27,  5.84it/s]

 48%|█████████████████████████████▍                               | 473/980 [01:20<01:27,  5.80it/s]

 48%|█████████████████████████████▌                               | 474/980 [01:20<01:26,  5.83it/s]

 48%|█████████████████████████████▌                               | 475/980 [01:21<01:25,  5.87it/s]

 49%|█████████████████████████████▋                               | 476/980 [01:21<01:25,  5.89it/s]

 49%|█████████████████████████████▋                               | 477/980 [01:21<01:25,  5.90it/s]

 49%|█████████████████████████████▊                               | 478/980 [01:21<01:24,  5.92it/s]

 49%|█████████████████████████████▊                               | 479/980 [01:21<01:24,  5.94it/s]

 49%|█████████████████████████████▉                               | 480/980 [01:21<01:24,  5.95it/s]

 49%|█████████████████████████████▉                               | 481/980 [01:22<01:23,  5.94it/s]

 49%|██████████████████████████████                               | 482/980 [01:22<01:23,  5.94it/s]

 49%|██████████████████████████████                               | 483/980 [01:22<01:23,  5.93it/s]

 49%|██████████████████████████████▏                              | 484/980 [01:22<01:23,  5.92it/s]

 49%|██████████████████████████████▏                              | 485/980 [01:22<01:23,  5.92it/s]

 50%|██████████████████████████████▎                              | 486/980 [01:22<01:23,  5.92it/s]

 50%|██████████████████████████████▎                              | 487/980 [01:23<01:23,  5.94it/s]

 50%|██████████████████████████████▍                              | 488/980 [01:23<01:22,  5.95it/s]

 50%|██████████████████████████████▍                              | 489/980 [01:23<01:22,  5.95it/s]

 50%|██████████████████████████████▌                              | 490/980 [01:23<01:22,  5.95it/s]

 50%|██████████████████████████████▌                              | 491/980 [01:23<01:22,  5.96it/s]

 50%|██████████████████████████████▌                              | 492/980 [01:23<01:21,  5.96it/s]

 50%|██████████████████████████████▋                              | 493/980 [01:24<01:21,  5.95it/s]

 50%|██████████████████████████████▋                              | 494/980 [01:24<01:23,  5.83it/s]

 51%|██████████████████████████████▊                              | 495/980 [01:24<01:23,  5.84it/s]

 51%|██████████████████████████████▊                              | 496/980 [01:24<01:22,  5.86it/s]

 51%|██████████████████████████████▉                              | 497/980 [01:24<01:22,  5.85it/s]

 51%|██████████████████████████████▉                              | 498/980 [01:24<01:22,  5.85it/s]

 51%|███████████████████████████████                              | 499/980 [01:25<01:22,  5.86it/s]

 51%|███████████████████████████████                              | 500/980 [01:25<01:21,  5.88it/s]

 51%|███████████████████████████████▏                             | 501/980 [01:25<01:21,  5.90it/s]

 51%|███████████████████████████████▏                             | 502/980 [01:25<01:21,  5.83it/s]

 51%|███████████████████████████████▎                             | 503/980 [01:25<01:22,  5.80it/s]

 51%|███████████████████████████████▎                             | 504/980 [01:25<01:21,  5.84it/s]

 52%|███████████████████████████████▍                             | 505/980 [01:26<01:21,  5.86it/s]

 52%|███████████████████████████████▍                             | 506/980 [01:26<01:20,  5.87it/s]

 52%|███████████████████████████████▌                             | 507/980 [01:26<01:20,  5.88it/s]

 52%|███████████████████████████████▌                             | 508/980 [01:26<01:20,  5.87it/s]

 52%|███████████████████████████████▋                             | 509/980 [01:26<01:20,  5.89it/s]

 52%|███████████████████████████████▋                             | 510/980 [01:26<01:19,  5.90it/s]

 52%|███████████████████████████████▊                             | 511/980 [01:27<01:19,  5.90it/s]

 52%|███████████████████████████████▊                             | 512/980 [01:27<01:19,  5.91it/s]

 52%|███████████████████████████████▉                             | 513/980 [01:27<01:19,  5.91it/s]

 52%|███████████████████████████████▉                             | 514/980 [01:27<01:18,  5.91it/s]

 53%|████████████████████████████████                             | 515/980 [01:27<01:18,  5.91it/s]

 53%|████████████████████████████████                             | 516/980 [01:27<01:18,  5.91it/s]

 53%|████████████████████████████████▏                            | 517/980 [01:28<01:18,  5.93it/s]

 53%|████████████████████████████████▏                            | 518/980 [01:28<01:20,  5.75it/s]

 53%|████████████████████████████████▎                            | 519/980 [01:28<01:20,  5.74it/s]

 53%|████████████████████████████████▎                            | 520/980 [01:28<01:19,  5.77it/s]

 53%|████████████████████████████████▍                            | 521/980 [01:28<01:19,  5.81it/s]

 53%|████████████████████████████████▍                            | 522/980 [01:29<01:18,  5.83it/s]

 53%|████████████████████████████████▌                            | 523/980 [01:29<01:18,  5.86it/s]

 53%|████████████████████████████████▌                            | 524/980 [01:29<01:17,  5.87it/s]

 54%|████████████████████████████████▋                            | 525/980 [01:29<01:17,  5.88it/s]

 54%|████████████████████████████████▋                            | 526/980 [01:29<01:17,  5.88it/s]

 54%|████████████████████████████████▊                            | 527/980 [01:29<01:16,  5.90it/s]

 54%|████████████████████████████████▊                            | 528/980 [01:30<01:16,  5.88it/s]

 54%|████████████████████████████████▉                            | 529/980 [01:30<01:16,  5.90it/s]

 54%|████████████████████████████████▉                            | 530/980 [01:30<01:27,  5.17it/s]

 54%|█████████████████████████████████                            | 531/980 [01:30<01:24,  5.33it/s]

 54%|█████████████████████████████████                            | 532/980 [01:30<01:22,  5.46it/s]

 54%|█████████████████████████████████▏                           | 533/980 [01:30<01:20,  5.55it/s]

 54%|█████████████████████████████████▏                           | 534/980 [01:31<01:19,  5.62it/s]

 55%|█████████████████████████████████▎                           | 535/980 [01:31<01:18,  5.67it/s]

 55%|█████████████████████████████████▎                           | 536/980 [01:31<01:17,  5.71it/s]

 55%|█████████████████████████████████▍                           | 537/980 [01:31<01:17,  5.73it/s]

 55%|█████████████████████████████████▍                           | 538/980 [01:31<01:16,  5.75it/s]

 55%|█████████████████████████████████▌                           | 539/980 [01:32<01:16,  5.76it/s]

 55%|█████████████████████████████████▌                           | 540/980 [01:32<01:16,  5.78it/s]

 55%|█████████████████████████████████▋                           | 541/980 [01:32<01:15,  5.80it/s]

 55%|█████████████████████████████████▋                           | 542/980 [01:32<01:15,  5.83it/s]

 55%|█████████████████████████████████▊                           | 543/980 [01:32<01:14,  5.83it/s]

 56%|█████████████████████████████████▊                           | 544/980 [01:32<01:14,  5.84it/s]

 56%|█████████████████████████████████▉                           | 545/980 [01:33<01:14,  5.86it/s]

 56%|█████████████████████████████████▉                           | 546/980 [01:33<01:14,  5.86it/s]

 56%|██████████████████████████████████                           | 547/980 [01:33<01:13,  5.86it/s]

 56%|██████████████████████████████████                           | 548/980 [01:33<01:13,  5.89it/s]

 56%|██████████████████████████████████▏                          | 549/980 [01:33<01:13,  5.88it/s]

 56%|██████████████████████████████████▏                          | 550/980 [01:33<01:13,  5.89it/s]

 56%|██████████████████████████████████▎                          | 551/980 [01:34<01:12,  5.90it/s]

 56%|██████████████████████████████████▎                          | 552/980 [01:34<01:12,  5.91it/s]

 56%|██████████████████████████████████▍                          | 553/980 [01:34<01:12,  5.91it/s]

 57%|██████████████████████████████████▍                          | 554/980 [01:34<01:12,  5.91it/s]

 57%|██████████████████████████████████▌                          | 555/980 [01:34<01:11,  5.91it/s]

 57%|██████████████████████████████████▌                          | 556/980 [01:34<01:11,  5.90it/s]

 57%|██████████████████████████████████▋                          | 557/980 [01:35<01:11,  5.91it/s]

 57%|██████████████████████████████████▋                          | 558/980 [01:35<01:11,  5.90it/s]

 57%|██████████████████████████████████▊                          | 559/980 [01:35<01:11,  5.90it/s]

 57%|██████████████████████████████████▊                          | 560/980 [01:35<01:11,  5.91it/s]

 57%|██████████████████████████████████▉                          | 561/980 [01:35<01:10,  5.91it/s]

 57%|██████████████████████████████████▉                          | 562/980 [01:35<01:10,  5.91it/s]

 57%|███████████████████████████████████                          | 563/980 [01:36<01:10,  5.92it/s]

 58%|███████████████████████████████████                          | 564/980 [01:36<01:10,  5.92it/s]

 58%|███████████████████████████████████▏                         | 565/980 [01:36<01:10,  5.88it/s]

 58%|███████████████████████████████████▏                         | 566/980 [01:36<01:10,  5.88it/s]

 58%|███████████████████████████████████▎                         | 567/980 [01:36<01:10,  5.87it/s]

 58%|███████████████████████████████████▎                         | 568/980 [01:36<01:10,  5.84it/s]

 58%|███████████████████████████████████▍                         | 569/980 [01:37<01:10,  5.85it/s]

 58%|███████████████████████████████████▍                         | 570/980 [01:37<01:09,  5.86it/s]

 58%|███████████████████████████████████▌                         | 571/980 [01:37<01:09,  5.88it/s]

 58%|███████████████████████████████████▌                         | 572/980 [01:37<01:09,  5.89it/s]

 58%|███████████████████████████████████▋                         | 573/980 [01:37<01:09,  5.88it/s]

 59%|███████████████████████████████████▋                         | 574/980 [01:37<01:09,  5.85it/s]

 59%|███████████████████████████████████▊                         | 575/980 [01:38<01:09,  5.86it/s]

 59%|███████████████████████████████████▊                         | 576/980 [01:38<01:08,  5.86it/s]

 59%|███████████████████████████████████▉                         | 577/980 [01:38<01:08,  5.85it/s]

 59%|███████████████████████████████████▉                         | 578/980 [01:38<01:08,  5.86it/s]

 59%|████████████████████████████████████                         | 579/980 [01:38<01:08,  5.81it/s]

 59%|████████████████████████████████████                         | 580/980 [01:38<01:08,  5.82it/s]

 59%|████████████████████████████████████▏                        | 581/980 [01:39<01:08,  5.83it/s]

 59%|████████████████████████████████████▏                        | 582/980 [01:39<01:08,  5.85it/s]

 59%|████████████████████████████████████▎                        | 583/980 [01:39<01:07,  5.85it/s]

 60%|████████████████████████████████████▎                        | 584/980 [01:39<01:07,  5.87it/s]

 60%|████████████████████████████████████▍                        | 585/980 [01:39<01:07,  5.88it/s]

 60%|████████████████████████████████████▍                        | 586/980 [01:39<01:06,  5.88it/s]

 60%|████████████████████████████████████▌                        | 587/980 [01:40<01:06,  5.88it/s]

 60%|████████████████████████████████████▌                        | 588/980 [01:40<01:06,  5.88it/s]

 60%|████████████████████████████████████▋                        | 589/980 [01:40<01:06,  5.88it/s]

 60%|████████████████████████████████████▋                        | 590/980 [01:40<01:06,  5.90it/s]

 60%|████████████████████████████████████▊                        | 591/980 [01:40<01:06,  5.89it/s]

 60%|████████████████████████████████████▊                        | 592/980 [01:41<01:05,  5.88it/s]

 61%|████████████████████████████████████▉                        | 593/980 [01:41<01:05,  5.87it/s]

 61%|████████████████████████████████████▉                        | 594/980 [01:41<01:05,  5.88it/s]

 61%|█████████████████████████████████████                        | 595/980 [01:41<01:05,  5.89it/s]

 61%|█████████████████████████████████████                        | 596/980 [01:41<01:05,  5.89it/s]

 61%|█████████████████████████████████████▏                       | 597/980 [01:41<01:04,  5.90it/s]

 61%|█████████████████████████████████████▏                       | 598/980 [01:42<01:04,  5.91it/s]

 61%|█████████████████████████████████████▎                       | 599/980 [01:42<01:04,  5.91it/s]

 61%|█████████████████████████████████████▎                       | 600/980 [01:42<01:04,  5.92it/s]

 61%|█████████████████████████████████████▍                       | 601/980 [01:42<01:04,  5.88it/s]

 61%|█████████████████████████████████████▍                       | 602/980 [01:42<01:04,  5.84it/s]

 62%|█████████████████████████████████████▌                       | 603/980 [01:42<01:05,  5.79it/s]

 62%|█████████████████████████████████████▌                       | 604/980 [01:43<01:04,  5.81it/s]

 62%|█████████████████████████████████████▋                       | 605/980 [01:43<01:04,  5.84it/s]

 62%|█████████████████████████████████████▋                       | 606/980 [01:43<01:03,  5.85it/s]

 62%|█████████████████████████████████████▊                       | 607/980 [01:43<01:03,  5.87it/s]

 62%|█████████████████████████████████████▊                       | 608/980 [01:43<01:03,  5.89it/s]

 62%|█████████████████████████████████████▉                       | 609/980 [01:43<01:02,  5.89it/s]

 62%|█████████████████████████████████████▉                       | 610/980 [01:44<01:03,  5.86it/s]

 62%|██████████████████████████████████████                       | 611/980 [01:44<01:03,  5.86it/s]

 62%|██████████████████████████████████████                       | 612/980 [01:44<01:02,  5.84it/s]

 63%|██████████████████████████████████████▏                      | 613/980 [01:44<01:03,  5.82it/s]

 63%|██████████████████████████████████████▏                      | 614/980 [01:44<01:02,  5.83it/s]

 63%|██████████████████████████████████████▎                      | 615/980 [01:44<01:02,  5.82it/s]

 63%|██████████████████████████████████████▎                      | 616/980 [01:45<01:02,  5.80it/s]

 63%|██████████████████████████████████████▍                      | 617/980 [01:45<01:02,  5.83it/s]

 63%|██████████████████████████████████████▍                      | 618/980 [01:45<01:03,  5.74it/s]

 63%|██████████████████████████████████████▌                      | 619/980 [01:45<01:02,  5.74it/s]

 63%|██████████████████████████████████████▌                      | 620/980 [01:45<01:02,  5.76it/s]

 63%|██████████████████████████████████████▋                      | 621/980 [01:45<01:01,  5.81it/s]

 63%|██████████████████████████████████████▋                      | 622/980 [01:46<01:01,  5.83it/s]

 64%|██████████████████████████████████████▊                      | 623/980 [01:46<01:00,  5.86it/s]

 64%|██████████████████████████████████████▊                      | 624/980 [01:46<01:00,  5.86it/s]

 64%|██████████████████████████████████████▉                      | 625/980 [01:46<01:00,  5.88it/s]

 64%|██████████████████████████████████████▉                      | 626/980 [01:46<01:00,  5.89it/s]

 64%|███████████████████████████████████████                      | 627/980 [01:46<00:59,  5.90it/s]

 64%|███████████████████████████████████████                      | 628/980 [01:47<00:59,  5.87it/s]

 64%|███████████████████████████████████████▏                     | 629/980 [01:47<00:59,  5.86it/s]

 64%|███████████████████████████████████████▏                     | 630/980 [01:47<00:59,  5.88it/s]

 64%|███████████████████████████████████████▎                     | 631/980 [01:47<00:59,  5.87it/s]

 64%|███████████████████████████████████████▎                     | 632/980 [01:47<00:59,  5.89it/s]

 65%|███████████████████████████████████████▍                     | 633/980 [01:48<00:58,  5.89it/s]

 65%|███████████████████████████████████████▍                     | 634/980 [01:48<00:58,  5.89it/s]

 65%|███████████████████████████████████████▌                     | 635/980 [01:48<00:58,  5.89it/s]

 65%|███████████████████████████████████████▌                     | 636/980 [01:48<00:58,  5.87it/s]

 65%|███████████████████████████████████████▋                     | 637/980 [01:48<00:58,  5.87it/s]

 65%|███████████████████████████████████████▋                     | 638/980 [01:48<00:58,  5.88it/s]

 65%|███████████████████████████████████████▊                     | 639/980 [01:49<00:57,  5.90it/s]

 65%|███████████████████████████████████████▊                     | 640/980 [01:49<00:57,  5.90it/s]

 65%|███████████████████████████████████████▉                     | 641/980 [01:49<00:57,  5.90it/s]

 66%|███████████████████████████████████████▉                     | 642/980 [01:49<00:57,  5.90it/s]

 66%|████████████████████████████████████████                     | 643/980 [01:49<00:57,  5.91it/s]

 66%|████████████████████████████████████████                     | 644/980 [01:49<00:57,  5.89it/s]

 66%|████████████████████████████████████████▏                    | 645/980 [01:50<00:56,  5.88it/s]

 66%|████████████████████████████████████████▏                    | 646/980 [01:50<00:56,  5.88it/s]

 66%|████████████████████████████████████████▎                    | 647/980 [01:50<00:56,  5.89it/s]

 66%|████████████████████████████████████████▎                    | 648/980 [01:50<00:56,  5.89it/s]

 66%|████████████████████████████████████████▍                    | 649/980 [01:50<00:56,  5.90it/s]

 66%|████████████████████████████████████████▍                    | 650/980 [01:50<00:56,  5.89it/s]

 66%|████████████████████████████████████████▌                    | 651/980 [01:51<00:56,  5.83it/s]

 67%|████████████████████████████████████████▌                    | 652/980 [01:51<00:56,  5.84it/s]

 67%|████████████████████████████████████████▋                    | 653/980 [01:51<00:55,  5.87it/s]

 67%|████████████████████████████████████████▋                    | 654/980 [01:51<00:55,  5.88it/s]

 67%|████████████████████████████████████████▊                    | 655/980 [01:51<00:55,  5.87it/s]

 67%|████████████████████████████████████████▊                    | 656/980 [01:51<00:55,  5.88it/s]

 67%|████████████████████████████████████████▉                    | 657/980 [01:52<00:55,  5.87it/s]

 67%|████████████████████████████████████████▉                    | 658/980 [01:52<00:54,  5.87it/s]

 67%|█████████████████████████████████████████                    | 659/980 [01:52<00:54,  5.88it/s]

 67%|█████████████████████████████████████████                    | 660/980 [01:52<00:54,  5.86it/s]

 67%|█████████████████████████████████████████▏                   | 661/980 [01:52<00:54,  5.86it/s]

 68%|█████████████████████████████████████████▏                   | 662/980 [01:52<00:54,  5.87it/s]

 68%|█████████████████████████████████████████▎                   | 663/980 [01:53<00:53,  5.87it/s]

 68%|█████████████████████████████████████████▎                   | 664/980 [01:53<00:54,  5.81it/s]

 68%|█████████████████████████████████████████▍                   | 665/980 [01:53<00:54,  5.82it/s]

 68%|█████████████████████████████████████████▍                   | 666/980 [01:53<00:53,  5.84it/s]

 68%|█████████████████████████████████████████▌                   | 667/980 [01:53<00:53,  5.88it/s]

 68%|█████████████████████████████████████████▌                   | 668/980 [01:53<00:52,  5.89it/s]

 68%|█████████████████████████████████████████▋                   | 669/980 [01:54<00:52,  5.91it/s]

 68%|█████████████████████████████████████████▋                   | 670/980 [01:54<00:52,  5.92it/s]

 68%|█████████████████████████████████████████▊                   | 671/980 [01:54<00:52,  5.91it/s]

 69%|█████████████████████████████████████████▊                   | 672/980 [01:54<00:52,  5.90it/s]

 69%|█████████████████████████████████████████▉                   | 673/980 [01:54<00:52,  5.90it/s]

 69%|█████████████████████████████████████████▉                   | 674/980 [01:54<00:51,  5.91it/s]

 69%|██████████████████████████████████████████                   | 675/980 [01:55<00:51,  5.90it/s]

 69%|██████████████████████████████████████████                   | 676/980 [01:55<00:51,  5.89it/s]

 69%|██████████████████████████████████████████▏                  | 677/980 [01:55<00:51,  5.87it/s]

 69%|██████████████████████████████████████████▏                  | 678/980 [01:55<00:51,  5.87it/s]

 69%|██████████████████████████████████████████▎                  | 679/980 [01:55<00:51,  5.89it/s]

 69%|██████████████████████████████████████████▎                  | 680/980 [01:56<00:50,  5.90it/s]

 69%|██████████████████████████████████████████▍                  | 681/980 [01:56<00:50,  5.91it/s]

 70%|██████████████████████████████████████████▍                  | 682/980 [01:56<00:50,  5.93it/s]

 70%|██████████████████████████████████████████▌                  | 683/980 [01:56<00:50,  5.93it/s]

 70%|██████████████████████████████████████████▌                  | 684/980 [01:56<00:49,  5.94it/s]

 70%|██████████████████████████████████████████▋                  | 685/980 [01:56<00:49,  5.94it/s]

 70%|██████████████████████████████████████████▋                  | 686/980 [01:57<00:49,  5.93it/s]

 70%|██████████████████████████████████████████▊                  | 687/980 [01:57<00:49,  5.92it/s]

 70%|██████████████████████████████████████████▊                  | 688/980 [01:57<00:49,  5.90it/s]

 70%|██████████████████████████████████████████▉                  | 689/980 [01:57<00:49,  5.89it/s]

 70%|██████████████████████████████████████████▉                  | 690/980 [01:57<00:49,  5.89it/s]

 71%|███████████████████████████████████████████                  | 691/980 [01:57<00:49,  5.89it/s]

 71%|███████████████████████████████████████████                  | 692/980 [01:58<00:48,  5.91it/s]

 71%|███████████████████████████████████████████▏                 | 693/980 [01:58<00:48,  5.89it/s]

 71%|███████████████████████████████████████████▏                 | 694/980 [01:58<00:48,  5.88it/s]

 71%|███████████████████████████████████████████▎                 | 695/980 [01:58<00:48,  5.87it/s]

 71%|███████████████████████████████████████████▎                 | 696/980 [01:58<00:48,  5.89it/s]

 71%|███████████████████████████████████████████▍                 | 697/980 [01:58<00:47,  5.90it/s]

 71%|███████████████████████████████████████████▍                 | 698/980 [01:59<00:47,  5.91it/s]

 71%|███████████████████████████████████████████▌                 | 699/980 [01:59<00:47,  5.90it/s]

 71%|███████████████████████████████████████████▌                 | 700/980 [01:59<00:47,  5.89it/s]

 72%|███████████████████████████████████████████▋                 | 701/980 [01:59<00:47,  5.87it/s]

 72%|███████████████████████████████████████████▋                 | 702/980 [01:59<00:47,  5.88it/s]

 72%|███████████████████████████████████████████▊                 | 703/980 [01:59<00:47,  5.88it/s]

 72%|███████████████████████████████████████████▊                 | 704/980 [02:00<00:46,  5.88it/s]

 72%|███████████████████████████████████████████▉                 | 705/980 [02:00<00:47,  5.82it/s]

 72%|███████████████████████████████████████████▉                 | 706/980 [02:00<00:47,  5.80it/s]

 72%|████████████████████████████████████████████                 | 707/980 [02:00<00:47,  5.81it/s]

 72%|████████████████████████████████████████████                 | 708/980 [02:00<00:46,  5.81it/s]

 72%|████████████████████████████████████████████▏                | 709/980 [02:00<00:46,  5.88it/s]

 72%|████████████████████████████████████████████▏                | 710/980 [02:01<00:45,  5.90it/s]

 73%|████████████████████████████████████████████▎                | 711/980 [02:01<00:45,  5.91it/s]

 73%|████████████████████████████████████████████▎                | 712/980 [02:01<00:45,  5.92it/s]

 73%|████████████████████████████████████████████▍                | 713/980 [02:01<00:44,  5.94it/s]

 73%|████████████████████████████████████████████▍                | 714/980 [02:01<00:44,  5.97it/s]

 73%|████████████████████████████████████████████▌                | 715/980 [02:01<00:44,  5.99it/s]

 73%|████████████████████████████████████████████▌                | 716/980 [02:02<00:44,  5.99it/s]

 73%|████████████████████████████████████████████▋                | 717/980 [02:02<00:44,  5.98it/s]

 73%|████████████████████████████████████████████▋                | 718/980 [02:02<00:43,  5.97it/s]

 73%|████████████████████████████████████████████▊                | 719/980 [02:02<00:43,  5.96it/s]

 73%|████████████████████████████████████████████▊                | 720/980 [02:02<00:43,  5.95it/s]

 74%|████████████████████████████████████████████▉                | 721/980 [02:02<00:43,  5.95it/s]

 74%|████████████████████████████████████████████▉                | 722/980 [02:03<00:43,  5.94it/s]

 74%|█████████████████████████████████████████████                | 723/980 [02:03<00:43,  5.98it/s]

 74%|█████████████████████████████████████████████                | 724/980 [02:03<00:43,  5.93it/s]

 74%|█████████████████████████████████████████████▏               | 725/980 [02:03<00:43,  5.92it/s]

 74%|█████████████████████████████████████████████▏               | 726/980 [02:03<00:42,  5.91it/s]

 74%|█████████████████████████████████████████████▎               | 727/980 [02:03<00:42,  5.91it/s]

 74%|█████████████████████████████████████████████▎               | 728/980 [02:04<00:42,  5.91it/s]

 74%|█████████████████████████████████████████████▍               | 729/980 [02:04<00:42,  5.91it/s]

 74%|█████████████████████████████████████████████▍               | 730/980 [02:04<00:42,  5.91it/s]

 75%|█████████████████████████████████████████████▌               | 731/980 [02:04<00:42,  5.90it/s]

 75%|█████████████████████████████████████████████▌               | 732/980 [02:04<00:41,  5.91it/s]

 75%|█████████████████████████████████████████████▋               | 733/980 [02:04<00:41,  5.91it/s]

 75%|█████████████████████████████████████████████▋               | 734/980 [02:05<00:41,  5.89it/s]

 75%|█████████████████████████████████████████████▊               | 735/980 [02:05<00:41,  5.93it/s]

 75%|█████████████████████████████████████████████▊               | 736/980 [02:05<00:40,  5.96it/s]

 75%|█████████████████████████████████████████████▊               | 737/980 [02:05<00:41,  5.90it/s]

 75%|█████████████████████████████████████████████▉               | 738/980 [02:05<00:41,  5.86it/s]

 75%|█████████████████████████████████████████████▉               | 739/980 [02:06<00:41,  5.83it/s]

 76%|██████████████████████████████████████████████               | 740/980 [02:06<00:41,  5.81it/s]

 76%|██████████████████████████████████████████████               | 741/980 [02:06<00:41,  5.72it/s]

 76%|██████████████████████████████████████████████▏              | 742/980 [02:06<00:41,  5.77it/s]

 76%|██████████████████████████████████████████████▏              | 743/980 [02:06<00:40,  5.81it/s]

 76%|██████████████████████████████████████████████▎              | 744/980 [02:06<00:40,  5.82it/s]

 76%|██████████████████████████████████████████████▎              | 745/980 [02:07<00:40,  5.84it/s]

 76%|██████████████████████████████████████████████▍              | 746/980 [02:07<00:39,  5.85it/s]

 76%|██████████████████████████████████████████████▍              | 747/980 [02:07<00:39,  5.87it/s]

 76%|██████████████████████████████████████████████▌              | 748/980 [02:07<00:39,  5.87it/s]

 76%|██████████████████████████████████████████████▌              | 749/980 [02:07<00:39,  5.87it/s]

 77%|██████████████████████████████████████████████▋              | 750/980 [02:07<00:39,  5.87it/s]

 77%|██████████████████████████████████████████████▋              | 751/980 [02:08<00:39,  5.87it/s]

 77%|██████████████████████████████████████████████▊              | 752/980 [02:08<00:38,  5.87it/s]

 77%|██████████████████████████████████████████████▊              | 753/980 [02:08<00:38,  5.87it/s]

 77%|██████████████████████████████████████████████▉              | 754/980 [02:08<00:38,  5.87it/s]

 77%|██████████████████████████████████████████████▉              | 755/980 [02:08<00:38,  5.90it/s]

 77%|███████████████████████████████████████████████              | 756/980 [02:08<00:38,  5.88it/s]

 77%|███████████████████████████████████████████████              | 757/980 [02:09<00:37,  5.88it/s]

 77%|███████████████████████████████████████████████▏             | 758/980 [02:09<00:37,  5.89it/s]

 77%|███████████████████████████████████████████████▏             | 759/980 [02:09<00:37,  5.82it/s]

 78%|███████████████████████████████████████████████▎             | 760/980 [02:09<00:37,  5.86it/s]

 78%|███████████████████████████████████████████████▎             | 761/980 [02:09<00:37,  5.90it/s]

 78%|███████████████████████████████████████████████▍             | 762/980 [02:09<00:37,  5.80it/s]

 78%|███████████████████████████████████████████████▍             | 763/980 [02:10<00:37,  5.86it/s]

 78%|███████████████████████████████████████████████▌             | 764/980 [02:10<00:36,  5.88it/s]

 78%|███████████████████████████████████████████████▌             | 765/980 [02:10<00:36,  5.87it/s]

 78%|███████████████████████████████████████████████▋             | 766/980 [02:10<00:36,  5.87it/s]

 78%|███████████████████████████████████████████████▋             | 767/980 [02:10<00:36,  5.91it/s]

 78%|███████████████████████████████████████████████▊             | 768/980 [02:10<00:35,  5.89it/s]

 78%|███████████████████████████████████████████████▊             | 769/980 [02:11<00:35,  5.88it/s]

 79%|███████████████████████████████████████████████▉             | 770/980 [02:11<00:35,  5.91it/s]

 79%|███████████████████████████████████████████████▉             | 771/980 [02:11<00:35,  5.92it/s]

 79%|████████████████████████████████████████████████             | 772/980 [02:11<00:34,  5.96it/s]

 79%|████████████████████████████████████████████████             | 773/980 [02:11<00:34,  5.99it/s]

 79%|████████████████████████████████████████████████▏            | 774/980 [02:11<00:35,  5.88it/s]

 79%|████████████████████████████████████████████████▏            | 775/980 [02:12<00:34,  5.86it/s]

 79%|████████████████████████████████████████████████▎            | 776/980 [02:12<00:34,  5.92it/s]

 79%|████████████████████████████████████████████████▎            | 777/980 [02:12<00:34,  5.96it/s]

 79%|████████████████████████████████████████████████▍            | 778/980 [02:12<00:33,  6.00it/s]

 79%|████████████████████████████████████████████████▍            | 779/980 [02:12<00:33,  6.03it/s]

 80%|████████████████████████████████████████████████▌            | 780/980 [02:12<00:33,  6.03it/s]

 80%|████████████████████████████████████████████████▌            | 781/980 [02:13<00:32,  6.05it/s]

 80%|████████████████████████████████████████████████▋            | 782/980 [02:13<00:32,  6.05it/s]

 80%|████████████████████████████████████████████████▋            | 783/980 [02:13<00:32,  6.03it/s]

 80%|████████████████████████████████████████████████▊            | 784/980 [02:13<00:32,  6.02it/s]

 80%|████████████████████████████████████████████████▊            | 785/980 [02:13<00:32,  6.04it/s]

 80%|████████████████████████████████████████████████▉            | 786/980 [02:13<00:32,  5.99it/s]

 80%|████████████████████████████████████████████████▉            | 787/980 [02:14<00:32,  5.91it/s]

 80%|█████████████████████████████████████████████████            | 788/980 [02:14<00:32,  5.87it/s]

 81%|█████████████████████████████████████████████████            | 789/980 [02:14<00:32,  5.87it/s]

 81%|█████████████████████████████████████████████████▏           | 790/980 [02:14<00:32,  5.86it/s]

 81%|█████████████████████████████████████████████████▏           | 791/980 [02:14<00:32,  5.84it/s]

 81%|█████████████████████████████████████████████████▎           | 792/980 [02:14<00:32,  5.82it/s]

 81%|█████████████████████████████████████████████████▎           | 793/980 [02:15<00:32,  5.79it/s]

 81%|█████████████████████████████████████████████████▍           | 794/980 [02:15<00:32,  5.77it/s]

 81%|█████████████████████████████████████████████████▍           | 795/980 [02:15<00:32,  5.77it/s]

 81%|█████████████████████████████████████████████████▌           | 796/980 [02:15<00:31,  5.76it/s]

 81%|█████████████████████████████████████████████████▌           | 797/980 [02:15<00:31,  5.75it/s]

 81%|█████████████████████████████████████████████████▋           | 798/980 [02:16<00:31,  5.72it/s]

 82%|█████████████████████████████████████████████████▋           | 799/980 [02:16<00:31,  5.76it/s]

 82%|█████████████████████████████████████████████████▊           | 800/980 [02:16<00:31,  5.81it/s]

 82%|█████████████████████████████████████████████████▊           | 801/980 [02:16<00:30,  5.84it/s]

 82%|█████████████████████████████████████████████████▉           | 802/980 [02:16<00:30,  5.85it/s]

 82%|█████████████████████████████████████████████████▉           | 803/980 [02:16<00:30,  5.86it/s]

 82%|██████████████████████████████████████████████████           | 804/980 [02:17<00:30,  5.84it/s]

 82%|██████████████████████████████████████████████████           | 805/980 [02:17<00:29,  5.86it/s]

 82%|██████████████████████████████████████████████████▏          | 806/980 [02:17<00:29,  5.88it/s]

 82%|██████████████████████████████████████████████████▏          | 807/980 [02:17<00:29,  5.89it/s]

 82%|██████████████████████████████████████████████████▎          | 808/980 [02:17<00:29,  5.88it/s]

 83%|██████████████████████████████████████████████████▎          | 809/980 [02:17<00:29,  5.89it/s]

 83%|██████████████████████████████████████████████████▍          | 810/980 [02:18<00:28,  5.89it/s]

 83%|██████████████████████████████████████████████████▍          | 811/980 [02:18<00:28,  5.89it/s]

 83%|██████████████████████████████████████████████████▌          | 812/980 [02:18<00:28,  5.89it/s]

 83%|██████████████████████████████████████████████████▌          | 813/980 [02:18<00:28,  5.87it/s]

 83%|██████████████████████████████████████████████████▋          | 814/980 [02:18<00:28,  5.88it/s]

 83%|██████████████████████████████████████████████████▋          | 815/980 [02:18<00:27,  5.90it/s]

 83%|██████████████████████████████████████████████████▊          | 816/980 [02:19<00:27,  5.92it/s]

 83%|██████████████████████████████████████████████████▊          | 817/980 [02:19<00:27,  5.92it/s]

 83%|██████████████████████████████████████████████████▉          | 818/980 [02:19<00:27,  5.92it/s]

 84%|██████████████████████████████████████████████████▉          | 819/980 [02:19<00:27,  5.91it/s]

 84%|███████████████████████████████████████████████████          | 820/980 [02:19<00:27,  5.89it/s]

 84%|███████████████████████████████████████████████████          | 821/980 [02:19<00:27,  5.88it/s]

 84%|███████████████████████████████████████████████████▏         | 822/980 [02:20<00:26,  5.88it/s]

 84%|███████████████████████████████████████████████████▏         | 823/980 [02:20<00:26,  5.88it/s]

 84%|███████████████████████████████████████████████████▎         | 824/980 [02:20<00:26,  5.90it/s]

 84%|███████████████████████████████████████████████████▎         | 825/980 [02:20<00:26,  5.89it/s]

 84%|███████████████████████████████████████████████████▍         | 826/980 [02:20<00:26,  5.89it/s]

 84%|███████████████████████████████████████████████████▍         | 827/980 [02:20<00:25,  5.89it/s]

 84%|███████████████████████████████████████████████████▌         | 828/980 [02:21<00:25,  5.90it/s]

 85%|███████████████████████████████████████████████████▌         | 829/980 [02:21<00:25,  5.92it/s]

 85%|███████████████████████████████████████████████████▋         | 830/980 [02:21<00:25,  5.91it/s]

 85%|███████████████████████████████████████████████████▋         | 831/980 [02:21<00:29,  5.07it/s]

 85%|███████████████████████████████████████████████████▊         | 832/980 [02:21<00:28,  5.26it/s]

 85%|███████████████████████████████████████████████████▊         | 833/980 [02:22<00:27,  5.40it/s]

 85%|███████████████████████████████████████████████████▉         | 834/980 [02:22<00:26,  5.52it/s]

 85%|███████████████████████████████████████████████████▉         | 835/980 [02:22<00:25,  5.59it/s]

 85%|████████████████████████████████████████████████████         | 836/980 [02:22<00:25,  5.65it/s]

 85%|████████████████████████████████████████████████████         | 837/980 [02:22<00:25,  5.68it/s]

 86%|████████████████████████████████████████████████████▏        | 838/980 [02:22<00:24,  5.71it/s]

 86%|████████████████████████████████████████████████████▏        | 839/980 [02:23<00:24,  5.73it/s]

 86%|████████████████████████████████████████████████████▎        | 840/980 [02:23<00:24,  5.76it/s]

 86%|████████████████████████████████████████████████████▎        | 841/980 [02:23<00:24,  5.77it/s]

 86%|████████████████████████████████████████████████████▍        | 842/980 [02:23<00:24,  5.69it/s]

 86%|████████████████████████████████████████████████████▍        | 843/980 [02:23<00:24,  5.70it/s]

 86%|████████████████████████████████████████████████████▌        | 844/980 [02:23<00:23,  5.76it/s]

 86%|████████████████████████████████████████████████████▌        | 845/980 [02:24<00:23,  5.79it/s]

 86%|████████████████████████████████████████████████████▋        | 846/980 [02:24<00:22,  5.83it/s]

 86%|████████████████████████████████████████████████████▋        | 847/980 [02:24<00:22,  5.85it/s]

 87%|████████████████████████████████████████████████████▊        | 848/980 [02:24<00:22,  5.88it/s]

 87%|████████████████████████████████████████████████████▊        | 849/980 [02:24<00:22,  5.88it/s]

 87%|████████████████████████████████████████████████████▉        | 850/980 [02:25<00:22,  5.90it/s]

 87%|████████████████████████████████████████████████████▉        | 851/980 [02:25<00:21,  5.90it/s]

 87%|█████████████████████████████████████████████████████        | 852/980 [02:25<00:21,  5.91it/s]

 87%|█████████████████████████████████████████████████████        | 853/980 [02:25<00:21,  5.91it/s]

 87%|█████████████████████████████████████████████████████▏       | 854/980 [02:25<00:21,  5.91it/s]

 87%|█████████████████████████████████████████████████████▏       | 855/980 [02:25<00:21,  5.91it/s]

 87%|█████████████████████████████████████████████████████▎       | 856/980 [02:26<00:20,  5.91it/s]

 87%|█████████████████████████████████████████████████████▎       | 857/980 [02:26<00:20,  5.91it/s]

 88%|█████████████████████████████████████████████████████▍       | 858/980 [02:26<00:20,  5.90it/s]

 88%|█████████████████████████████████████████████████████▍       | 859/980 [02:26<00:20,  5.90it/s]

 88%|█████████████████████████████████████████████████████▌       | 860/980 [02:26<00:20,  5.91it/s]

 88%|█████████████████████████████████████████████████████▌       | 861/980 [02:26<00:20,  5.91it/s]

 88%|█████████████████████████████████████████████████████▋       | 862/980 [02:27<00:19,  5.92it/s]

 88%|█████████████████████████████████████████████████████▋       | 863/980 [02:27<00:19,  5.92it/s]

 88%|█████████████████████████████████████████████████████▊       | 864/980 [02:27<00:19,  5.93it/s]

 88%|█████████████████████████████████████████████████████▊       | 865/980 [02:27<00:19,  5.94it/s]

 88%|█████████████████████████████████████████████████████▉       | 866/980 [02:27<00:19,  5.93it/s]

 88%|█████████████████████████████████████████████████████▉       | 867/980 [02:27<00:18,  5.95it/s]

 89%|██████████████████████████████████████████████████████       | 868/980 [02:28<00:18,  5.94it/s]

 89%|██████████████████████████████████████████████████████       | 869/980 [02:28<00:18,  5.92it/s]

 89%|██████████████████████████████████████████████████████▏      | 870/980 [02:28<00:18,  5.93it/s]

 89%|██████████████████████████████████████████████████████▏      | 871/980 [02:28<00:18,  5.91it/s]

 89%|██████████████████████████████████████████████████████▎      | 872/980 [02:28<00:18,  5.92it/s]

 89%|██████████████████████████████████████████████████████▎      | 873/980 [02:28<00:18,  5.92it/s]

 89%|██████████████████████████████████████████████████████▍      | 874/980 [02:29<00:17,  5.94it/s]

 89%|██████████████████████████████████████████████████████▍      | 875/980 [02:29<00:17,  5.93it/s]

 89%|██████████████████████████████████████████████████████▌      | 876/980 [02:29<00:17,  5.93it/s]

 89%|██████████████████████████████████████████████████████▌      | 877/980 [02:29<00:17,  5.93it/s]

 90%|██████████████████████████████████████████████████████▋      | 878/980 [02:29<00:17,  5.93it/s]

 90%|██████████████████████████████████████████████████████▋      | 879/980 [02:29<00:17,  5.94it/s]

 90%|██████████████████████████████████████████████████████▊      | 880/980 [02:30<00:16,  5.91it/s]

 90%|██████████████████████████████████████████████████████▊      | 881/980 [02:30<00:16,  5.88it/s]

 90%|██████████████████████████████████████████████████████▉      | 882/980 [02:30<00:16,  5.87it/s]

 90%|██████████████████████████████████████████████████████▉      | 883/980 [02:30<00:16,  5.79it/s]

 90%|███████████████████████████████████████████████████████      | 884/980 [02:30<00:16,  5.79it/s]

 90%|███████████████████████████████████████████████████████      | 885/980 [02:30<00:16,  5.81it/s]

 90%|███████████████████████████████████████████████████████▏     | 886/980 [02:31<00:16,  5.82it/s]

 91%|███████████████████████████████████████████████████████▏     | 887/980 [02:31<00:16,  5.79it/s]

 91%|███████████████████████████████████████████████████████▎     | 888/980 [02:31<00:15,  5.82it/s]

 91%|███████████████████████████████████████████████████████▎     | 889/980 [02:31<00:15,  5.85it/s]

 91%|███████████████████████████████████████████████████████▍     | 890/980 [02:31<00:15,  5.86it/s]

 91%|███████████████████████████████████████████████████████▍     | 891/980 [02:31<00:15,  5.87it/s]

 91%|███████████████████████████████████████████████████████▌     | 892/980 [02:32<00:14,  5.87it/s]

 91%|███████████████████████████████████████████████████████▌     | 893/980 [02:32<00:14,  5.85it/s]

 91%|███████████████████████████████████████████████████████▋     | 894/980 [02:32<00:14,  5.87it/s]

 91%|███████████████████████████████████████████████████████▋     | 895/980 [02:32<00:14,  5.89it/s]

 91%|███████████████████████████████████████████████████████▊     | 896/980 [02:32<00:14,  5.91it/s]

 92%|███████████████████████████████████████████████████████▊     | 897/980 [02:32<00:14,  5.93it/s]

 92%|███████████████████████████████████████████████████████▉     | 898/980 [02:33<00:13,  5.93it/s]

 92%|███████████████████████████████████████████████████████▉     | 899/980 [02:33<00:13,  5.95it/s]

 92%|████████████████████████████████████████████████████████     | 900/980 [02:33<00:13,  5.95it/s]

 92%|████████████████████████████████████████████████████████     | 901/980 [02:33<00:13,  5.95it/s]

 92%|████████████████████████████████████████████████████████▏    | 902/980 [02:33<00:13,  5.95it/s]

 92%|████████████████████████████████████████████████████████▏    | 903/980 [02:33<00:12,  5.95it/s]

 92%|████████████████████████████████████████████████████████▎    | 904/980 [02:34<00:12,  5.94it/s]

 92%|████████████████████████████████████████████████████████▎    | 905/980 [02:34<00:12,  5.93it/s]

 92%|████████████████████████████████████████████████████████▍    | 906/980 [02:34<00:12,  5.92it/s]

 93%|████████████████████████████████████████████████████████▍    | 907/980 [02:34<00:12,  5.92it/s]

 93%|████████████████████████████████████████████████████████▌    | 908/980 [02:34<00:12,  5.93it/s]

 93%|████████████████████████████████████████████████████████▌    | 909/980 [02:34<00:11,  5.94it/s]

 93%|████████████████████████████████████████████████████████▋    | 910/980 [02:35<00:11,  5.94it/s]

 93%|████████████████████████████████████████████████████████▋    | 911/980 [02:35<00:11,  5.94it/s]

 93%|████████████████████████████████████████████████████████▊    | 912/980 [02:35<00:11,  5.94it/s]

 93%|████████████████████████████████████████████████████████▊    | 913/980 [02:35<00:11,  5.94it/s]

 93%|████████████████████████████████████████████████████████▉    | 914/980 [02:35<00:11,  5.94it/s]

 93%|████████████████████████████████████████████████████████▉    | 915/980 [02:36<00:10,  5.94it/s]

 93%|█████████████████████████████████████████████████████████    | 916/980 [02:36<00:10,  5.93it/s]

 94%|█████████████████████████████████████████████████████████    | 917/980 [02:36<00:10,  5.92it/s]

 94%|█████████████████████████████████████████████████████████▏   | 918/980 [02:36<00:10,  5.92it/s]

 94%|█████████████████████████████████████████████████████████▏   | 919/980 [02:36<00:10,  5.91it/s]

 94%|█████████████████████████████████████████████████████████▎   | 920/980 [02:36<00:10,  5.92it/s]

 94%|█████████████████████████████████████████████████████████▎   | 921/980 [02:37<00:09,  5.93it/s]

 94%|█████████████████████████████████████████████████████████▍   | 922/980 [02:37<00:09,  5.93it/s]

 94%|█████████████████████████████████████████████████████████▍   | 923/980 [02:37<00:09,  5.93it/s]

 94%|█████████████████████████████████████████████████████████▌   | 924/980 [02:37<00:09,  5.93it/s]

 94%|█████████████████████████████████████████████████████████▌   | 925/980 [02:37<00:09,  5.91it/s]

 94%|█████████████████████████████████████████████████████████▋   | 926/980 [02:37<00:09,  5.92it/s]

 95%|█████████████████████████████████████████████████████████▋   | 927/980 [02:38<00:09,  5.89it/s]

 95%|█████████████████████████████████████████████████████████▊   | 928/980 [02:38<00:08,  5.86it/s]

 95%|█████████████████████████████████████████████████████████▊   | 929/980 [02:38<00:08,  5.89it/s]

 95%|█████████████████████████████████████████████████████████▉   | 930/980 [02:38<00:08,  5.91it/s]

 95%|█████████████████████████████████████████████████████████▉   | 931/980 [02:38<00:08,  5.92it/s]

 95%|██████████████████████████████████████████████████████████   | 932/980 [02:38<00:08,  5.93it/s]

 95%|██████████████████████████████████████████████████████████   | 933/980 [02:39<00:07,  5.94it/s]

 95%|██████████████████████████████████████████████████████████▏  | 934/980 [02:39<00:07,  5.93it/s]

 95%|██████████████████████████████████████████████████████████▏  | 935/980 [02:39<00:07,  5.91it/s]

 96%|██████████████████████████████████████████████████████████▎  | 936/980 [02:39<00:07,  5.90it/s]

 96%|██████████████████████████████████████████████████████████▎  | 937/980 [02:39<00:07,  5.91it/s]

 96%|██████████████████████████████████████████████████████████▍  | 938/980 [02:39<00:07,  5.85it/s]

 96%|██████████████████████████████████████████████████████████▍  | 939/980 [02:40<00:07,  5.81it/s]

 96%|██████████████████████████████████████████████████████████▌  | 940/980 [02:40<00:06,  5.86it/s]

 96%|██████████████████████████████████████████████████████████▌  | 941/980 [02:40<00:06,  5.89it/s]

 96%|██████████████████████████████████████████████████████████▋  | 942/980 [02:40<00:06,  5.91it/s]

 96%|██████████████████████████████████████████████████████████▋  | 943/980 [02:40<00:06,  5.94it/s]

 96%|██████████████████████████████████████████████████████████▊  | 944/980 [02:40<00:06,  5.98it/s]

 96%|██████████████████████████████████████████████████████████▊  | 945/980 [02:41<00:05,  6.01it/s]

 97%|██████████████████████████████████████████████████████████▉  | 946/980 [02:41<00:05,  6.02it/s]

 97%|██████████████████████████████████████████████████████████▉  | 947/980 [02:41<00:05,  6.02it/s]

 97%|███████████████████████████████████████████████████████████  | 948/980 [02:41<00:05,  6.03it/s]

 97%|███████████████████████████████████████████████████████████  | 949/980 [02:41<00:05,  6.02it/s]

 97%|███████████████████████████████████████████████████████████▏ | 950/980 [02:41<00:04,  6.02it/s]

 97%|███████████████████████████████████████████████████████████▏ | 951/980 [02:42<00:04,  6.02it/s]

 97%|███████████████████████████████████████████████████████████▎ | 952/980 [02:42<00:04,  6.03it/s]

 97%|███████████████████████████████████████████████████████████▎ | 953/980 [02:42<00:04,  6.02it/s]

 97%|███████████████████████████████████████████████████████████▍ | 954/980 [02:42<00:04,  6.04it/s]

 97%|███████████████████████████████████████████████████████████▍ | 955/980 [02:42<00:04,  6.04it/s]

 98%|███████████████████████████████████████████████████████████▌ | 956/980 [02:42<00:03,  6.01it/s]

 98%|███████████████████████████████████████████████████████████▌ | 957/980 [02:43<00:03,  5.95it/s]

 98%|███████████████████████████████████████████████████████████▋ | 958/980 [02:43<00:03,  5.90it/s]

 98%|███████████████████████████████████████████████████████████▋ | 959/980 [02:43<00:03,  5.86it/s]

 98%|███████████████████████████████████████████████████████████▊ | 960/980 [02:43<00:03,  5.84it/s]

 98%|███████████████████████████████████████████████████████████▊ | 961/980 [02:43<00:03,  5.82it/s]

 98%|███████████████████████████████████████████████████████████▉ | 962/980 [02:43<00:03,  5.83it/s]

 98%|███████████████████████████████████████████████████████████▉ | 963/980 [02:44<00:02,  5.82it/s]

 98%|████████████████████████████████████████████████████████████ | 964/980 [02:44<00:02,  5.82it/s]

 98%|████████████████████████████████████████████████████████████ | 965/980 [02:44<00:02,  5.81it/s]

 99%|████████████████████████████████████████████████████████████▏| 966/980 [02:44<00:02,  5.82it/s]

 99%|████████████████████████████████████████████████████████████▏| 967/980 [02:44<00:02,  5.79it/s]

 99%|████████████████████████████████████████████████████████████▎| 968/980 [02:44<00:02,  5.80it/s]

 99%|████████████████████████████████████████████████████████████▎| 969/980 [02:45<00:01,  5.82it/s]

 99%|████████████████████████████████████████████████████████████▍| 970/980 [02:45<00:01,  5.83it/s]

 99%|████████████████████████████████████████████████████████████▍| 971/980 [02:45<00:01,  5.85it/s]

 99%|████████████████████████████████████████████████████████████▌| 972/980 [02:45<00:01,  5.88it/s]

 99%|████████████████████████████████████████████████████████████▌| 973/980 [02:45<00:01,  5.92it/s]

 99%|████████████████████████████████████████████████████████████▋| 974/980 [02:45<00:01,  5.92it/s]

 99%|████████████████████████████████████████████████████████████▋| 975/980 [02:46<00:00,  5.91it/s]

100%|████████████████████████████████████████████████████████████▊| 976/980 [02:46<00:00,  5.92it/s]

100%|████████████████████████████████████████████████████████████▊| 977/980 [02:46<00:00,  5.91it/s]

100%|████████████████████████████████████████████████████████████▉| 978/980 [02:46<00:00,  5.92it/s]

100%|████████████████████████████████████████████████████████████▉| 979/980 [02:46<00:00,  5.94it/s]

100%|█████████████████████████████████████████████████████████████| 980/980 [02:46<00:00,  5.94it/s]

100%|█████████████████████████████████████████████████████████████| 980/980 [02:46<00:00,  5.87it/s]

'Skipped files: 0'

In [9]:
predictions = pd.concat(predictions, ignore_index=True)
display(predictions.shape)
display(predictions.head())

(671300, 8)

,trait,drug,score,true_class,method,n_top_genes,data,tissue
0,DOID:0050741,DB00215,103099.5,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
1,DOID:0050741,DB00704,355210.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
2,DOID:0050741,DB00822,388169.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
3,DOID:10283,DB00014,80190.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
4,DOID:10283,DB00175,232448.0,0,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous

## Validation checks (enforces NB06–NB09 completeness, copied from signif_test/00)

In [10]:
assert not predictions.isna().any().any()

_method_counts = predictions['method'].value_counts().reindex(EXPECTED_METHODS)
display(_method_counts)

N_PREDICTIONS = predictions[['drug', 'trait']].drop_duplicates().shape[0]
display(f'Unique drug-disease pairs: {N_PREDICTIONS}')

for method_name, thresholds in METHOD_THRESHOLDS.items():
    expected = N_TISSUES * len(thresholds) * N_PREDICTIONS
    actual = int(_method_counts.loc[method_name])
    assert actual == expected, (
        f'{method_name}: expected {expected}, got {actual} -- '
        f'{_METHOD_SOURCE_NB[method_name]} must be complete '
        f'({N_TISSUES} tissues x {len(thresholds)} thresholds)')

# Tissue count sanity: exactly 49 distinct tissues, identical across methods.
_n_tissues = predictions.groupby('method', observed=True)['tissue'].nunique()
display(_n_tissues)
assert (_n_tissues == N_TISSUES).all(), 'tissue coverage is not a constant 49 across methods'
display('OK: completeness asserts pass (49 tissues x 5 thresholds x 685 pairs per method).')

method
gene_based               167825
module_based_archs4      167825
module_based_gtex        167825
module_based_recount2    167825
Name: count, dtype: int64

'Unique drug-disease pairs: 685'

method
gene_based               49
module_based_archs4      49
module_based_gtex        49
module_based_recount2    49
Name: tissue, dtype: int64

'OK: completeness asserts pass (49 tissues x 5 thresholds x 685 pairs per method).'

# Aggregate to per-tissue scores (mean over thresholds — **no max**)

Average ranks across the 5 `n_top_genes` thresholds (per trait, drug, method, tissue). This is
**step 1** of `signif_test/00`; we deliberately **stop before** the `groupby([trait, drug,
method]).max()` over tissues. The result keeps the tissue axis so each tissue can be scored
independently.

In [11]:
def _reduce_mean(x):
    return pd.Series({
        'score': x['score'].mean(),
        'true_class': x['true_class'].unique()[0],
    })


per_tissue_scores = (
    predictions
    .groupby(['trait', 'drug', 'method', 'tissue'], observed=True)
    .apply(_reduce_mean, include_groups=False)
    .dropna()
    .sort_index()
    .reset_index()
)
per_tissue_scores['method'] = pd.Categorical(
    per_tissue_scores['method'], categories=METHOD_ORDER, ordered=True)
display(per_tissue_scores.shape)
display(per_tissue_scores.head())

# 685 pairs x 4 methods x 49 tissues.
assert per_tissue_scores.shape[0] == len(EXPECTED_METHODS) * N_PREDICTIONS * N_TISSUES
assert per_tissue_scores.dropna().shape == per_tissue_scores.shape

(134260, 6)

,trait,drug,method,tissue,score,true_class
0,DOID:0050741,DB00215,gene_based,Adipose_Subcutaneous,52786.3,1.0
1,DOID:0050741,DB00215,gene_based,Adipose_Visceral_Omentum,73871.9,1.0
2,DOID:0050741,DB00215,gene_based,Adrenal_Gland,165504.3,1.0
3,DOID:0050741,DB00215,gene_based,Artery_Aorta,83904.3,1.0
4,DOID:0050741,DB00215,gene_based,Artery_Coronary,161434.9,1.0

In [12]:
out_scores = OUTPUT_DIR / 'per_tissue_scores.pkl'
per_tissue_scores.to_pickle(out_scores)
display(out_scores)

PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/tissue_agg_test/per_tissue_scores.pkl')

# Per-tissue metrics

For each `(method, tissue)` group (the 685 pairs scored in that single tissue) compute AUROC, AUPRC,
and `auprc_log2_enrich = log2(AUPRC / base_rate)`. The 685-pair label split is **constant across
tissues** (every tissue scores the identical pair universe), so both classes are always present and
every per-tissue metric is defined — no eligibility filtering is needed (unlike `per_disease_test`,
where the *disease* node varied).

In [13]:
def _tissue_metrics(g):
    y = g['true_class'].values.astype(int)
    s = g['score'].values
    n_total = len(y)
    n_pos = int(y.sum())
    n_neg = n_total - n_pos
    base_rate = n_pos / n_total
    auroc = roc_auc_score(y, s)
    auprc = average_precision_score(y, s)
    auprc_log2_enrich = float(np.log2(auprc / base_rate))
    return pd.Series({
        'n_pos': n_pos,
        'n_neg': n_neg,
        'n_total': n_total,
        'base_rate': base_rate,
        'auroc': auroc,
        'auprc': auprc,
        'auprc_log2_enrich': auprc_log2_enrich,
    })


per_tissue = (
    per_tissue_scores
    .groupby(['method', 'tissue'], observed=True)
    .apply(_tissue_metrics, include_groups=False)
    .reset_index()
)
per_tissue['method'] = pd.Categorical(per_tissue['method'], categories=METHOD_ORDER, ordered=True)
for c in ['n_pos', 'n_neg', 'n_total']:
    per_tissue[c] = per_tissue[c].astype(int)
for c in ['base_rate', 'auroc', 'auprc', 'auprc_log2_enrich']:
    per_tissue[c] = per_tissue[c].astype(float)
per_tissue = per_tissue.sort_values(['method', 'tissue']).reset_index(drop=True)

display(per_tissue.shape)
display(per_tissue.head())

# 4 methods x 49 tissues, no NaNs, constant label split across tissues.
assert per_tissue.shape[0] == len(METHOD_ORDER) * N_TISSUES
assert not per_tissue.isna().any().any()
assert per_tissue['n_pos'].nunique() == 1 and per_tissue['n_neg'].nunique() == 1, (
    'label split is not constant across tissues')
display(f"Constant per-tissue label split: {per_tissue['n_pos'].iloc[0]} pos / "
        f"{per_tissue['n_neg'].iloc[0]} neg (base_rate={per_tissue['base_rate'].iloc[0]:.4f})")

(196, 9)

,method,tissue,n_pos,n_neg,n_total,base_rate,auroc,auprc,auprc_log2_enrich
0,gene_based,Adipose_Subcutaneous,531,154,685,0.775182,0.523045,0.810025,0.063430
1,gene_based,Adipose_Visceral_Omentum,531,154,685,0.775182,0.530065,0.808614,0.060914
2,gene_based,Adrenal_Gland,531,154,685,0.775182,0.492657,0.807052,0.058125
3,gene_based,Artery_Aorta,531,154,685,0.775182,0.534626,0.819678,0.080521
4,gene_based,Artery_Coronary,531,154,685,0.775182,0.555403,0.823885,0.087907

'Constant per-tissue label split: 531 pos / 154 neg (base_rate=0.7752)'

In [14]:
# Macro-mean per-tissue AUROC by method (the aggregate-over-tissues estimand).
display(
    per_tissue.groupby('method', observed=True)[['auroc', 'auprc', 'auprc_log2_enrich']]
    .mean().reindex(METHOD_ORDER))

out_csv = OUTPUT_DIR / 'per_tissue_metrics.csv'
per_tissue.to_csv(out_csv, index=False)
display(out_csv)

                          auroc     auprc  auprc_log2_enrich
method
gene_based             0.541501  0.819369           0.079870
module_based_archs4    0.554696  0.824258           0.088317
module_based_gtex      0.526682  0.808470           0.060354
module_based_recount2  0.547066  0.820508           0.081838

PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/tissue_agg_test/per_tissue_metrics.csv')

# Max-aggregate reference (status quo)

Recompute the published **max-over-tissues** pooled AUROC/AUPRC per method directly from
`../signif_test/predictions_paired.pkl`. This is the number the per-tissue aggregate is contrasted
against in NB01 — it must reproduce 0.583 / 0.625 / 0.602 / 0.612 (gene / archs4 / gtex / recount2),
confirming our input frame matches `signif_test`.

In [15]:
paired = pd.read_pickle(PAIRED_PKL)
display(paired.shape)

_base_rate = paired.loc[paired['method'] == METHOD_ORDER[0], 'true_class'].mean()
rows = []
for m in METHOD_ORDER:
    g = paired[paired['method'] == m]
    y = g['true_class'].values.astype(int)
    s = g['score'].values
    auprc = average_precision_score(y, s)
    rows.append({
        'method': m,
        'auroc': roc_auc_score(y, s),
        'auprc': auprc,
        'auprc_log2_enrich': float(np.log2(auprc / (y.sum() / len(y)))),
    })
max_aggregate_reference = pd.DataFrame(rows)
display(max_aggregate_reference.round(4))

# Sanity tie-back to signif_test / NB10.
_expected = {'gene_based': 0.583, 'module_based_archs4': 0.625,
             'module_based_gtex': 0.602, 'module_based_recount2': 0.612}
for _, r in max_aggregate_reference.iterrows():
    assert abs(r['auroc'] - _expected[r['method']]) < 0.005, (
        f"max-aggregate AUROC for {r['method']} = {r['auroc']:.4f}, "
        f"expected ~{_expected[r['method']]}")
display('OK: max-aggregate AUROC reproduces signif_test (0.583 / 0.625 / 0.602 / 0.612).')

out_ref = OUTPUT_DIR / 'max_aggregate_reference.csv'
max_aggregate_reference.to_csv(out_ref, index=False)
display(out_ref)

(2740, 5)

                  method   auroc   auprc  auprc_log2_enrich
0             gene_based  0.5834  0.8449             0.1243
1    module_based_archs4  0.6254  0.8496             0.1323
2      module_based_gtex  0.6025  0.8393             0.1147
3  module_based_recount2  0.6123  0.8458             0.1258

'OK: max-aggregate AUROC reproduces signif_test (0.583 / 0.625 / 0.602 / 0.612).'

PosixPath('/home/miltondp/projects/clamp/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/tissue_agg_test/max_aggregate_reference.csv')